<!DOCTYPE html>
<html lang="en" manifest='jywebcacheapp.manifest'>
<head>
    <meta charset="utf-8">
    <title>爱用交易管理</title>
    <script type="text/javascript" src="http://g.alicdn.com/sj/lib/jquery/dist/jquery.min.js" ></script>
    <link href="http://g.alicdn.com/sj/qnui/1.1.6/css/sui.min.css" rel="stylesheet"/>
	<script type="text/javascript" src="http://g.alicdn.com/sj/qnui/1.1.6/js/sui.min.js" ></script>
	<script src="http://cdn.zzgdapp.com/pubcdn/handlebars-1.0.1.js"></script>
    <link rel="stylesheet/less" href="http://cdn.zzgdapp.com/trade/web/js/theme.less">
    <script type="text/javascript" src="http://g.tbcdn.cn/sj/qn/lib/js/less.js"></script>
    <script src="http://g.tbcdn.cn/sj/qn/jssdk.js"></script>
    <script src="http://cdn.zzgdapp.com/pubcdn/layer/layer.min.js"></script>
    <script src="http://cdn.zzgdapp.com/trade/web/js/superslide.js"></script>
	<script src="http://cdn.zzgdapp.com/trade/web/js/jquery-barcode-1.3.3.js"></script>
</head>
<body style="padding:0;overflow-y: hidden;overflow-x: hidden;" >
<div id="sendcontent" >
	<div style="border:1px dashed #000;width:330px;height:530px;font-family:黑体;">
	<div style="width:135px;height:72px;float:left;font-size:24px;text-align:center;line-height:70px;">标准快递</div>
	<div style="width:195px;height:72px;float:right;margin-left:-5px;"><div style="margin-left:40px;margin-top:5px;" class="facecode"></div></div>
	<div style="width:165px;height:55px;float:left;line-height:13px;font-size:12px;">寄件：<span class="fname">寄件</span>&nbsp;<span class="fmobile">寄件</span><br/><span style="margin-left: 35px;" class="shopName">寄件</span><br/><span style="margin-left: 35px;" class="faddress">寄件</span></div>
	<div style="width:161px;height:68px;font-size:40px;text-align:center;float:right;line-height:60px;"  class="facemdd">格口</div>
	<div style="width:165px;height:20px;float:left;line-height:13px;">收件：<span class="sname" style="font-size:16px;">收件</span>&nbsp;<span class="smobile" style="font-size:16px;">收件</span></div>
	<div style="width:330px;height:60px;float:left;line-height:13px;"><span style="margin-left: 35px;font-size:16px;" class="saddress">收件</span></div>
	<div style="width:135px;height:60px;float:left;line-height:13px;"><p></p>付款方式：<span></span><br/>计费重量：<span></span><br/>保价金额：<span></span></div>
	<div style="width:190px;height:60px;float:right;line-height:13px;margin-top:5px;">代件人\代收人：<span></span><br/>签收时间：<span style="line-height:13px;">&nbsp;&nbsp;&nbsp;&nbsp;</span>年<span style="">&nbsp;&nbsp;&nbsp;</span>月<span style="">&nbsp;&nbsp;&nbsp;</span>日<span style="width: 30px;">&nbsp;&nbsp;&nbsp;</span>时<br/><span style="margin-top:0px;line-height:9px;font-size: 9px;">快递送达收收货人地址，经收件人或收件人允许的代收件人签字视为送达。</span></div>
	<div style="width:330px;height:72px;float:left;line-height:13px;">订单号：<span class="facetid" ></span><span style="float:right;">件数：<span class="facenum"></span>重量：<span></span></span><br/>配货信息：<br/><span style="margin-left: 55px;" class="facebaby" ></span></div>
	<div style="width:330px;height:10px;float:left"></div>
	<div style="width:330px;height:26px;float:left;line-height:13px;"></div>
	<div style="width:135px;height:60px;float:left;line-height:13px;font-size: 10px;">寄件：<span class="fname">寄件</span>&nbsp;<span class="fmobile">寄件</span><br/><span style="margin-left: 35px;" class="shopName">寄件</span><br/><span style="margin-left: 35px;" class="faddress">寄件</span></div>
	<div style="width:190px;height:60px;float:right;line-height:13px;font-size: 10px;">收件：<span class="sname" style="font-size:16px;">收件</span>&nbsp;<span class="smobile" style="font-size:16px;">收件</span><br/><span style="margin-left: 35px;" class="saddress">收件</span></div>
	<div style="width:237px;height:60px;float:left;line-height:13px;">备注：收货前请确认包装是否完好，有无破损，如有问题，请拒绝签收</div>
	<div style="width:85px;height:88px;float:right" class="facetwo"></div>
	<div style="width:237px;height:22px;float:left;line-height:13px;">网址：www.ems.com.cn&nbsp;&nbsp;&nbsp;客服电话：11183</div>
	</div>
	<br/>
</div>
<script type="text/javascript">
	var  shash=window.location.hash.substr(1);
	var params = shash.split('&');
	var map = new HashMap();
	for (var i in params) {
	    var p = params[i].split("=");
	    if (p.length == 2) {
	        map.put(p[0], p[1]);
	    }
	}
	var babylist = decodeURIComponent(map.get("babylist"));
	$("#sendcontent").html(babylist);
	/*var twocodes=window.localStorage.getItem("twocode").split('|Y|');
	switch(twocodes[0]){
	case 'HTKY':{gettwoCode(twocodes[0],54,60,twocodes[2]); gettwoCode(twocodes[0]+'s',54,60,twocodes[1]);break;}
	case 'EMS':{gettwoCode(twocodes[0],80,80,twocodes[1]);break;}
	case 'EYB':{gettwoCode(twocodes[0],80,80,twocodes[1]);break;}
	case 'ZJS':{gettwoCode(twocodes[0],80,80,twocodes[1]);break;}
	case 'ZTO':{gettwoCode(twocodes[0],80,80,twocodes[1]);break;}
	case 'UC':{gettwoCode(twocodes[0],80,80,twocodes[1]);break;}
	}



	
	var fsmessages=fsmessage.split('|Y|');
	$(".fmobile").html(fsmessages[0]);
	$(".shopName").html(fsmessages[1]);
	$(".faddress").html(fsmessages[2]);
	$("#facetid").html(fsmessages[3]);
	var ssmessage=ssmessages.split('|Y|');
	$(".smobile").html(ssmessage[0]);
	$(".saddress").html(ssmessage[1]);
	var babylistxs=babylist.split('|,|');
	var babyvalx;
	var babyxval;
	for(index in babylistxs){
		babyxval=babylistxs[index].split('|:');
		if(babyvalx!='')babyvalx=babyxval[0]+' '+babyxval[2];else babyvalx=babyvalx+';'+babyxval[0]+' '+babyxval[2];
	}
	$("#facebaby").html(babyvalx);
	getfaceCode(fsmessages[4]);*/
/**
 * Created with need.
 * User: wangsx
 * Date: 14-5-22
 * Time: 16:20
 * 生成二维码.
 */
function gettwoCode(codeid,codewidth,codeheight,codeurl){
	$("#code_"+codeid).qrcode({
		render: "canvas",
		text: codeurl,
		width:codewidth,
		height:codeheight
		}); 
  } 
	
function HashMap(){var size=0;var entry=new Object();this.put=function(key,value){if(!this.containsKey(key)){size++}entry[key]=value};this.get=function(key){if(this.containsKey(key)){return entry[key]}else{return null}};this.remove=function(key){if(delete entry[key]){size--}};this.containsKey=function(key){return(key in entry)};this.containsValue=function(value){for(var prop in entry){if(entry[prop]==value){return true}}return false};this.values=function(){var values=new Array(size);for(var prop in entry){values.push(entry[prop])}return values};this.keys=function(){var keys=new Array(size);for(var prop in entry){keys.push(prop)}return keys};this.size=function(){return size}};
</script>
    </body>
    </html>
