<!DOCTYPE html>
<html lang="en" manifest='jywebcacheapp.manifest'>
<?php require_once ("app/views/public/head.php");?>
<style>
.well{
	min-height: 20px;
	padding: 19px;
	margin-bottom: 20px;
	background-color: #f5f5f5;
	border: 1px solid #e3e3e3;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
	-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.05);
	-moz-box-shadow: inset 0 1px 1px rgba(0,0,0,0.05);
	box-shadow: inset 0 1px 1px rgba(0,0,0,0.05)
}
</style>
<body>
<?php require_once ("app/views/public/top.php");?>
<div class="container" style="margin-left: 10px;"><br>
        <div style="display: none;" id="adv_top"></div>
        <div class="well">
            <h5 style="margin-top:0;">订单状态：<span id="tdsta"></span></h5>
            	<p id="gettimeinfo" style="text-align:left;"></p>
           <div class="alert" id="buyercon">
            </div>            
            <div style="text-align:left;" id="tdbtn">
            </div>
        </div>
        <div class="well" style="background-color:#fff;">
            <h5 style="margin-top:0;">订单信息</h5>
            <div class="sui-row-fluid">
                <div class="span6" id="tdbuy">
                    <p>买家昵称：</p>
                    <p>买家支付宝：</p>
                    <p>订单来源：</p>
                </div>
                <div class="span6" id="tdtid">
                    <p>订单编号：</p>
                    <p>支付宝交易号：</p>
                    <p>成交时间：</p>
                    <p>确认时间：</p>
                </div>
            </div>
            <table class="sui-table table-bordered table-striped table-hover" id="tditem">
            </table>                 
            <div id="tdprice">
            </div>                                 	
            <div id="codprice">
            </div>                                     
        </div>

<div id="infoitem" class="well"></div>    
    <table class="table table-bordered" >
        <tr>
            <td >
                    <div class="sui-row-fluid">
                                <div id="bfselects" >
            			<select  id="bfselect" onchange="showbg();"  >
						</select>
            			</div>
                        <div class="span12" id="tdwuliu">
                            <h5 style="margin-top:0;">收货和物流信息</h5>
                            <p>收货地址：
                                <button class="sui-btn btn-primary" >核对地址
                                </button>
                                <button class="sui-btn btn-primary">修改地址
                                </button>
                            </p>
                            <p>运送方式：</p>
                            <p>物流公司名称：</p>
                            <p>运单号：
                                <button class="sui-btn btn-primary"  >点击查看物流信息
                                </button>
                            </p>
                        </div>
                    </div>
            </td>
        </tr>
    </table>
        <div class="well" style="background-color:#fff;" id="wltab" style="display:none;">
                    <div class="sui-row-fluid">
                        <div class="span12" id="tdwldatas">

                        </div>
                    </div>
        </div>
 </div>
        <!--Profile Form货到付款 -->
	     <div id="sendcoditem-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:450px; width:560px;display:none;background-color:#FFF;">
			 <div class="mesWindowTop" style="height:35px;">
	            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
	            <h4>发货</h4>
	         </div>
			 <div class="modal-body" style="overflow:scroll;overflow-x:hidden; height: 300px;">
			 	<table class="table table-bordered" id="sendcodlist"></table>
                <b>选择我的发货地址：</b>
              <select id="selectaddrW" style="width: 400px;" >	              		          	    	             		
	          </select>
	           <br/>
	          <b>选择我的退货货地址：</b>
              <select id="selectbackaddrQ" style="width: 400px;" >	              		        	    	             		
	          </select> 
                <div class="row-fluid">
                    <b>请选择物流公司：</b>
                    <select id="codcomptyid">
                        <option  value='ZJS'>宅急送</option>
                        <option  value='YTO'>圆通速递</option>
                        <option  value='UAPEX'>全一快递</option>
                        <option  value='SF'>顺丰速递</option>
                        <option  value='FEDEX'>联邦快递</option>
                        <option  value='SCWL'>尚橙物流</option>
                        <option  value='GDEMS'>广东EMS</option>
                    </select>
                    <p style="margin: 0; padding: 0;"><b>运单号：</b><input  type="text"  class="span6" id="codpostid" value="" />
                    </p>
                </div>
			 </div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="codsendplan();" value="确定发货"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
		 </div>

          <!--Profile Form 订单改价-->
		  <div id="price-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:380px; width:560px;display:none;background-color:#FFF;">
			 <div class="mesWindowTop" style="height:35px;">
	            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
	            <h4>修改价格</h4>
	         </div>
			 <div class="modal-body" id="pricebody" style="overflow:scroll;overflow-x:hidden; height: 300px;">
             </div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="editprice();" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
		 </div>

		 <!--Profile Form订单属性修改  -->
		  <div id="skuedit-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:350px; width:560px;display:none;background-color:#FFF;">
			 <div class="mesWindowTop" style="height:35px;">
	            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
	            <h4>订单属性修改 </h4>
	         </div>
			 <div class="modal-body" id="skubody"></div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" id="savesku" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
		 </div>
		 
	  <!--Profile Form改邮费-->
	  <div id="editpost-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:250px; width:560px;display:none;background-color:#FFF;">
		 <div class="mesWindowTop" style="height:35px;">
            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
            <h4>修改免邮 </h4>
         </div>
		 <div class="modal-body">邮费将改为<input data-mini="true" type="text"  id="editpostval" style="width:88px;"/>元</div>
		<div class="footer">
			 <div  class="mesWindowBottom">	
				 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="editpost();" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
			 </div>
		 </div>
	 </div>
      <!--Profile Form免邮  -->
	  <div id="postfree-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:250px; width:560px;display:none;background-color:#FFF;">
		 <div class="mesWindowTop" style="height:35px;">
            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
            <h4>免邮 </h4>
         </div>
		 <div class="modal-body" ><p>邮费将改为0元</p></div>
		<div class="footer">
			 <div  class="mesWindowBottom">	
				 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="postfree();" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
			 </div>
		 </div>
	 </div>
        
        <!--Profile Form关闭订单  -->
     <div id="close-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:400px; width:560px;display:none;background-color:#FFF;">
		 <div class="mesWindowTop" style="height:35px;">
            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
            <h4>关闭订单 </h4>
         </div>
		 <div class="modal-body" style="overflow:scroll;overflow-x:hidden; max-height: 285px;">
		        <table class="table table-bordered" id="closelist">
                </table>
                <div class="alert" >请您在与买家达成一致的前提下，使用关闭交易这个功能哟!</div>
                <p style="margin-top: 20px;"><b>请选择关闭该交易的理由：</b>
                    <select id="tidclose" style="width:175px;" >
                        <option value="0">请选择关闭该交易的理由</option>
                        <option >未及时付款</option>
                        <option >买家联系不上</option>
                        <option >谢绝还价</option>
                        <option >商品瑕疵</option>
                        <option >协商不一致</option>
                        <option >买家不想买</option>
                        <option >与买家协商一致</option>
                    </select>
                </p>
                <span style="color: #ff9a00">温馨提示：</span>
                <p>1.为提升买家购物体验，您可以赠送买家店铺优惠券;</p>
                <p>2.拍下后减库存的商品，在关闭交易后，系统会自动恢复商品库存，但不会影响已下架商品的状态。</p>
            </div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="tidclose();" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
		 </div>
        
        <!--Profile Form修改备忘 -->
	     <div id="beiw-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:350px; width:560px;display:none;background-color:#FFF;">
			 <div class="mesWindowTop" style="height:35px;">
	            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
	            <h4>备忘 </h4>
	         </div>
			 <div class="modal-body" >
                <table  class="table table-striped table-bordered table-hover" style="width:530px;">
                    <tr ><td>标记(旗帜):</td><td>
                            <input style="margin-left: 20px" type="radio"  name="beiwf" value="1"  /><span   class="lbl"><img src="http://cdn.zzgdapp.com/trade/web/images/op_memo_1.png" width="12" alt="红"></span>
                            <input style="margin-left: 20px"  type="radio"  name="beiwf" value="2"  /><span   class="lbl"><img src="http://cdn.zzgdapp.com/trade/web/images/op_memo_2.png" width="12" alt="黄"></span>
                            <input style="margin-left: 20px"  type="radio"  name="beiwf" value="3"  /><span   class="lbl"><img src="http://cdn.zzgdapp.com/trade/web/images/op_memo_3.png" width="12" alt="绿"></span>
                            <input style="margin-left: 20px" type="radio"  name="beiwf" value="4"  /><span   class="lbl"><img src="http://cdn.zzgdapp.com/trade/web/images/op_memo_4.png" width="12" alt="蓝"></span>
                            <input style="margin-left: 20px" type="radio"  name="beiwf" value="5"  /><span   class="lbl"><img src="http://cdn.zzgdapp.com/trade/web/images/op_memo_5.png" width="12" alt="紫"></span>
                        </td></tr>
                    <tr ><td>选择常用短语:&nbsp;&nbsp;</td>
                        <td> <select onchange="memochoice();" style="width: 260px;"  class="conmemo"  id="memone">
                            </select>
                        </td></tr>
                    <tr ><td>卖家备注:</td>
                    	<td>
                    		<textarea class="span12" id="beiwtext"  style="margin-top: 5px;width:400px"></textarea>
                    	</td>
                    </tr>
                </table>
				<div class="alert" style="text-align:left;">淘宝网系统不会修改任何交易备忘请勿备注个人敏感信息。若不是本人填写，请小心被骗</div>
            </div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="addbeiw();" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
		 </div>
        
	 <!--Profile Form发货 -->
     <div id="senditem-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:440px; width:570px;display:none;background-color:#FFF;">
		 <div class="mesWindowTop" style="height:35px;">
            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
            <h4>发货</h4>
         </div>
		  <div class="modal-body" style="overflow:scroll;overflow-x:hidden; max-height: 325px;">
                <div class="row-fluid">
                    <div class="span6"><b>请选择发货方式：</b>
                        <select id="sendplan">
                            <option value='offline' >自己联系</option>
                            <option value='online'>在线下单</option>
                            <option value='notsend'>无需物流</option>
                        </select></div>
                    <div class="span6" id="wuliush1"><b>请选择物流公司：</b>
                        <select id="comptyid">

                        </select>
                    </div>
                </div>
                
                <div id="off_other">
                </div>
                <div id="wuliush2">
                <p style="margin: 0; padding: 0;"><b>运单号：</b><input  type="text"  class="span6" id="postid" value="" />
                </p>
                </div>
<table class="sui-table table-bordered" id="sendlist">
                </table>
                <div id="nohavasendaddr">
                	
                </div>
                <div id="selectsend">
                                <b>选择我的发货地址：</b>
              <select id="selectaddrQ" style="width: 400px;" >
	          </select>
	        <br/>
	        <b>选择我的退货地址：</b>
              <select id="selectbackaddr" style="width: 400px;" >
	          </select>
	          </div>
                <div class="alert">支持拆单发货；设置默认物流公司，方便您的发货</div>
            
            </div>
            
		<div class="footer">
			 <div  class="mesWindowBottom">	
				 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="sendplan();" value="确定发货"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
			 </div>
		 </div>
	 </div>
        
        <!--Profile Form修改发货 -->
	     <div id="resend-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:250px; width:560px;display:none;background-color:#FFF;">
			 <div class="mesWindowTop" style="height:35px;">
	            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
	            <h4>发货</h4>
	         </div>
			  <div class="modal-body" >
					<div id="on_line" ><p>请选择物流公司：
			        <div id="on_div">      
			         <select data-mini="true" name='ontrade' id='resendlist'>          
			         </select>
			        </div></p>
			         <p><span style="margin:0 -6px; font-size:12px; font-weight:normal;" class="font_wsl">请填写运单号码：</span> </p>
			         <input data-mini="true" type="text" name="outid" id="outid"/>
			         </div>
             </div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="toresends();" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
		 </div>

		 <!--Profile Form评价 -->
	     <div id="pingjia-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:420px; width:560px;display:none;background-color:#FFF;">
			 <div class="mesWindowTop" style="height:35px;">
	            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
	            <h4>评价</h4>
	         </div>
			  <div class="modal-body" id="pingjiadata" >
             </div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="pingjia();" value="确定评价"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
		 </div>

        <!--Profile Form延长收货时间 -->
		  <div id="shtime-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;height:220px; width:520px;display:none;background-color:#FFF;">
			 <div class="mesWindowTop" style="height:35px;">
	            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
	            <h4>延长收货时间</h4>
	         </div>
			 <div class="modal-body">
			 <p>延长收货时间可以让买家有更多时间来”确认收货“，而不会急于去申请退款。</p>
                <p style="margin-top: 20px;"><b>延长本交易的“确认收货”期限为：</b>
                    <select id="shday" style="width:100px;" >
                        <option value="3">3天</option>
                        <option value="5">5天</option>
                        <option value="7">7天</option>
                        <option value="10">10天</option>
                    </select>
                </p>
             </div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="shaddtime();" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
		 </div>
        
       <!-- 收货地址 -->
	  <div id="addr-table" class="mesWindow" style="Z-INDEX:99998; POSITION:absolute;width:520px;height:270px;display:none;background-color:#FFF;">
		 <div class="mesWindowTop" style="height:35px;">
            <button type="button" class="close" style="margin-top: 6px;" onclick="closeMsg('');">×</button>
            <h4>修改收货地址</h4>
         </div>
		 <div class="modal-body" >
			 <div class="control-group">
                        <div class="controls">
                            <span>省/市/区:</span>
                            <select style="width: 130px;" id="more_shen">
                                <!--   <option>省</option>-->
                            </select>
                            <select style="width: 130px;" id="more_shi">
                                <!--   <option>市</option>-->
                            </select >
                            <select style="width: 130px;" id="more_qu">
                                <!--  <option>区</option>-->
                            </select>
                        </div>
                        <div class="controls">
                            <span>邮政编码:</span>
                            <input style="width: 130px;" type="text" id="more_zip">
                        </div>
                        <div class="controls">
                            <span>收货人姓名:</span>
                            <input style="width: 130px;" type="text" id="more_name">
                            <span>街道地址:</span>
                            <input style="width: 150px;" type="text" id="more_address">
                        </div>
                        <div class="controls">
                            <span>电话:</span>
                            <input style="width: 130px;" type="text" id="more_phone">
                            <span>手机:</span>
                            <input style="width: 130px;" type="text" id="more_mobile">
                        </div>
                    </div>
	        </div>
			<div class="footer">
				 <div  class="mesWindowBottom">	
					 <input type="button" class="sui-btn btn-primary" style="padding: 3px 10px;" onclick="addeitd();" value="确定"><input type="button" onclick="closeMsg('');" style="margin-left:8px;padding: 3px 10px;" value="关闭">	
				 </div>
			 </div>
	  </div>
    <script type="text/javascript">
    var gtdsta='';
    var gtid='';
   	var gbeiwsta ='';
   	var gname='';
   	var gbuyernick='';
   	var gsellernick='';
   	var gtime='';
   	var gprdetail='';
   	var gmoreshen= '';
   	var gmoreshi='';
   	var gmorequ='';
    window.onload = function(){
        QN.initTheme();
        $("#indexsel").attr("class","dqzt");
        onload_viptime('tradedetail');
        setTimeout(gettbtime,10);/*淘宝时间*/       
        Handlebars.registerHelper('getFee', function(adjust_fee) {
               return (-Number(adjust_fee)).toFixed(2);
        });
        Handlebars.registerHelper('refundName', function(person,stam) {
                switch(person){
                    case 'WAIT_SELLER_AGREE':{return '退款中';break;}
                    case 'WAIT_BUYER_RETURN_GOODS':{return '退款中';break;}
                    case 'WAIT_SELLER_CONFIRM_GOODS':{return '退款中';break;}
                    case 'SELLER_REFUSE_BUYER':{return '已拒绝退款';break;}
                    case 'CLOSED':{return '退款关闭';break;}
                    case 'SUCCESS':{return '退款成功';break;}

                }
            switch(stam){
                case 'TRADE_NO_CREATE_PAY': return '待付款'; break;
                case 'WAIT_BUYER_PAY': return '待付款'; break;
                case 'WAIT_SELLER_SEND_GOODS': return '待发货'; break;
                case 'WAIT_BUYER_CONFIRM_GOODS': return '已发货'; break;
                case 'TRADE_BUYER_SIGNED': return '买家已签收'; break;
                case 'TRADE_FINISHED': return '已成功'; break;
                case 'TRADE_CLOSED': return '已取消'; break;
                case 'TRADE_CLOSED_BY_TAOBAO': return '已取消'; break;

            }
        });

        Handlebars.registerHelper('editpro', function(stam) {
                if(stam=='WAIT_SELLER_SEND_GOODS'){
                    return "修改订单属性";
                }else{
                    return "";
                }
        });
        var  shash=window.location.hash.substr(1);
        var params = shash.split('&');
        var map = new HashMap();
        for (var i in params) {
            var p = params[i].split("=");
            if (p.length == 2) {
                map.put(p[0], p[1]);
            }
        }
        gtid =map.get('tid');
        setTimeout(settaskcl,100);
        if(map.get('state')=='task'){
            $("#bt").html('任务管理');
            sta=map.get('sta');
        }
        setTimeout( getdetail,100);
        $("#sendplan").change(a_offline);
    }
    var taobaotime='';  
    var SysSecond; 
    var InterValObj;
    var typeinfo;/*详细信息，退款还是。。*/
    var uid;
    function reshow(){
    	gettbtime();/*重新获取淘宝时间*/
    	window.clearInterval(InterValObj);/*重新开始计时*/
    	getdetail();
    }
    function settaskcl(){
        QN.application.invoke({
            "cmd": "getVersion",
            "error" : function(msg) {
            },
            "success" : function(e) {
                if(typeof  e=== 'string'){
                    e = JSON.parse(e);
                }
                var version=e.version.replace(/[.]/g,"");
                version=version.replace(/[N]/g,"");
                if(version>=11200){
                    QN.application.invoke({
                        "cmd": "getLoginuser",
                        "success": function (e){
                            if(typeof  e=== 'string'){
                                e = JSON.parse(e);
                            }
                            if(e.sub_user_id==""){
                                uid=e.user_id;
                            }else{
                                uid=e.sub_user_id;
                            }
                            var param={};
                            param.fields="id,receiver_nick,status,biz_id,biz_nick,status,";
                            param.current_page=1;
                            param.biz_type="trade";
                            param.page_size=100;
                            param.receiver_uid=uid;
                            param.status="0,1,3,4,5";
                            param.biz_ids=gtid;
                            QN.top.invoke({
                                "cmd": "taobao.qianniu.tasks.get",
                                "param": param,
                                "method": "get",
                                "success": function (e){
                                    if(typeof  e=== 'string'){
                                        e = JSON.parse(e);
                                    }
                                    var resp=e.qianniu_tasks_get_response.tasks;
                                    resp=resp.q_task;
                                    if(resp){
                                         $("#tdbtn").prepend('&nbsp<a  onclick="cltask('+resp[0].id+')" id="clrw" style="float: right;color:#989898;" data-toggle="modal"><button class="sui-btn btn-small btn-warning">处理任务</button></a>');
                                    }
                                }
                            });
                        }
                    });
                }
            }
        });
    }
    

    function cltask(id){
        QN.component.invoke({
            category:'qtask_deal',
            param:{
                task_ids:[id]
            },
            error : function(msg, cmd, param) {
            },
            success : function(rsp, cmd, param) {
            	$("#hints").html('<p>任务处理成功！</p>');
              	showMsg('hint');
                $("#clrw").hide();
            }
        });
    }

        function gettbtime(){/*获取淘宝的系统时间*/        
      		 QN.top.invoke({
      		        "cmd": "taobao.time.get",
      		        "method": "get",
      		        "success":function (rsp){
      		            if(typeof rsp === 'string'){
      		                var    rsp = JSON.parse(rsp);
      		            }else{
      		                var	rsp= rsp;
      		            }
      		          taobaotime=rsp.time_get_response.time;           				            
      		          },
      		        error: function(msp){	
          		        taobaotime=GetDateStr(0);		       
      		        }
      		    });		    		      
      		}	
  			
        function DateDiff( sDate1, sDate2 )   /*获得两天的时间差*/
       	{
       		var diff;		
       		diff = sDate1.getTime() - sDate2.getTime();			//获得时间差,毫秒		
       		var day, hour, minute, second;
       		
       		day = Math.floor( diff / 86400000 );	//天  60*60*24*1000 = 86400000
       		diff -= day * 86400000; 
       		hour = Math.floor( diff / 3600000 );	//时
       		diff -= hour * 3600000;
       		minute = Math.floor( diff / 60000 );	//分
       		diff -= minute * 60000;
       		second = Math.floor( diff / 1000 );		//秒     
       		var sum=(day*24*60*60)+(hour*60*60)+(minute*60)+second;
       		if(sum!=0)
           		{
           			return sum;
           		}else{					
               		return 0;
               	}	
       		
       	}        	         
			
			//将时间减去1秒，计算天、时、分、秒 
			 function SetRemainTime() { 	 
			  if (SysSecond > 0) { 
			   SysSecond = SysSecond-1; 
			   var second = Math.floor(SysSecond % 60);             // 计算秒     
			   var minite = Math.floor((SysSecond / 60) % 60);      //计算分 
			   var hour = Math.floor((SysSecond / 3600) % 24);      //计算小时 
			   var day = Math.floor((SysSecond / 3600) / 24);        //计算天				  	 
				var info='<h6><font color= red >'+day+'天'+hour+'小时'+minite+'分'+second+'秒</font><font color=#000>'+ typeinfo +'</font></h6>';			  
				$("#gettimeinfo").html(info);							
			  } else {//剩余时间小于或等于0的时候，就停止间隔函数 
			   window.clearInterval(InterValObj); 
			   //这里可以添加倒计时时间为0后需要执行的事件 
			  } 
			 }
		       function gettimes(timestr,factor){/*获得factor天后的时间：例如2012-12-1 12:12"12 10天后是:2012-12-11 12:12:12*/
		       		var msTime = new Date(timestr).getTime();	
		          	var temptime = new Date();
		          	temptime.setTime( msTime + parseInt(factor*24*60*60000));
	          	 	return temptime.format( "yyyy-MM-dd hh:mm:ss");;
	          	 }

		       function totime(begin_time,nowtime,day)
		       {										
					var timestr=begin_time.replace(/-/g,"/");				
					var futuretime=gettimes(timestr,day)/*day天后的时间*/
					var listtime=DateDiff(new Date(futuretime),new Date(nowtime));	/*获得两个时间的时间差*/
					return listtime;
				}
        function changezhe(oid,price,num,zhe_fee)
        {

            var rval=$("#rebate-"+oid).val();
            if(isNaN(rval)==false){
                if(0==rval||''==rval||rval<0||rval>10){
                    $("#slider-"+oid).val('0');
                    $("#rebate-"+oid).val('0');
                }else{

                    var sval= Number(rval)*Number(price)/10-Number(num)*Number(price);

                    $("#slider-"+oid).val(sval.toFixed(2));
                }

                var postfee=$("#postval").val();
                var  oids='';
                var  vtadjust_fee=0;
                for(var i=0;i<goidarr.length;i++){
                    var  oids=goidarr[i];
                    /*   alert($("#slider-"+oids).val());*/
                    vtadjust_fee=Number(vtadjust_fee)+Number($("#slider-"+oids).val());
                }
                /*       alert(v);*/

              /*  var   vpricetotal= (Number(vtadjust_fee)+ Number(gtotal_fee)+Number(postfee)).toFixed(2);

                if(vtadjust_fee<0){
                    var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                }else{
                    var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                }*/
                var   vpricetotal= (Number(vtadjust_fee)+ Number(gtotal_fee)+Number(postfee)-Number(gprdetail)).toFixed(2);

                if(vtadjust_fee<0){
                    if(0==gprdetail){
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                    }else{
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' - '+gprdetail+' = '+ vpricetotal;
                    }
                }else{
                    if(0==gprdetail){
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                    }else{
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' - '+gprdetail+' = '+ vpricetotal;
                    }
                }

                $("#maijiashifu").empty();
                $("#maijiashifu").html(maijiashifu).trigger('create');
            }else{
                $("#rebate-"+oid).val('0')
                /*亲，价格必须是数字!*/
                Alert('亲，必须是数字!');
            }


        }
        function wangwang(bnick){
            var wangnick='cntaobao'+bnick;

            QN.wangwang.invoke({
                category: 'wangwang',
                cmd: 'chat',
                param: {'uid':wangnick},
                success: function (rsp) {

                },
                error: function (msg) {

                }
            });



        }
        function changepost()
        {


            var postfee=$("#postval").val();
            if(isNaN(postfee)==false){
                var  oids='';
                var  vtadjust_fee=0;
                for(var i=0;i<goidarr.length;i++){
                    var  oids=goidarr[i];
                    vtadjust_fee=Number(vtadjust_fee)+Number($("#slider-"+oids).val());
                }

             /*   var   vpricetotal= (Number(vtadjust_fee)+ Number(gtotal_fee)+Number(postfee)).toFixed(2);

                if(vtadjust_fee<0){
                    var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                }else{
                    var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                }*/
                var   vpricetotal= (Number(vtadjust_fee)+ Number(gtotal_fee)+Number(postfee)-Number(gprdetail)).toFixed(2);

                if(vtadjust_fee<0){
                    if(0==gprdetail)  {
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                    }else{
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' - '+gprdetail+' = '+ vpricetotal;
                    }
                }else{
                    if(0==gprdetail){
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                    }else{
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' - '+gprdetail+' = '+ vpricetotal;
                    }
                }

                $("#maijiashifu").empty();
                $("#maijiashifu").html(maijiashifu).trigger('create');
            }else{
                $("#postval").val('0')
                Alert('亲，必须是数字!');
            }

        }

        function changezhefee(oid,zhe_fee)
        {
           var sval= $("#slider-"+oid).val();
            if(isNaN(sval)==false){
                $("#rebate-"+oid).val('');
                var postfee=$("#postval").val();
                var  oids='';
                var  vtadjust_fee=0;
                for(var i=0;i<goidarr.length;i++){
                    var  oids=goidarr[i];
                    vtadjust_fee=Number(vtadjust_fee)+Number($("#slider-"+oids).val());
                }

           /*     var   vpricetotal= (Number(vtadjust_fee)+ Number(gtotal_fee)+Number(postfee)).toFixed(2);

                if(vtadjust_fee<0){
                    var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                }else{
                    var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                }*/

                var   vpricetotal= (Number(vtadjust_fee)+ Number(gtotal_fee)+Number(postfee)-Number(gprdetail)).toFixed(2);

                if(vtadjust_fee<0){
                    if(0==gprdetail){
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                    }else{
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' '+ vtadjust_fee.toFixed(2)+' - '+gprdetail+' = '+ vpricetotal;
                    }
                }else{
                    if(0==gprdetail){
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' = '+ vpricetotal;
                    }else{
                        var maijiashifu='买家实付：'+gtotal_fee +' + '+ postfee +' + '+vtadjust_fee.toFixed(2)+' - '+gprdetail+' = '+ vpricetotal;
                    }
                }



                $("#maijiashifu").empty();
                $("#maijiashifu").html(maijiashifu).trigger('create');
            }else{
                $("#slider-"+oid).val('0')
                Alert('亲，必须是数字!');
            }
        }
        function butrefresh(){
            loadaddress();
            getdetail();
            showMsg('addr-table');
        }

        function Alert(str) {
            var msgw,msgh,bordercolor;
            msgw=350;
            msgh=80;
            titleheight=25
            bordercolor="#336699";
            titlecolor="#99CCFF";
            var sWidth,sHeight;

            sWidth = document.body.offsetWidth;
            sHeight = document.body.offsetHeight;

            var bgObj=document.createElement("div");
            bgObj.setAttribute('id','alertbgDiv');
            bgObj.style.position="absolute";
            bgObj.style.top="0";
            bgObj.style.background="#E8E8E8";
            bgObj.style.filter="progid:DXImageTransform.Microsoft.Alpha(style=3,opacity=25,finishOpacity=75";
            bgObj.style.opacity="0.6";
            bgObj.style.left="0";
            bgObj.style.width = sWidth + "px";
            bgObj.style.height = sHeight + "px";
            bgObj.style.zIndex = "10000";
            document.body.appendChild(bgObj);

            var msgObj = document.createElement("div")
            msgObj.setAttribute("id","alertmsgDiv");
            msgObj.setAttribute("align","center");
            msgObj.style.background="white";
            msgObj.style.border="1px solid " + bordercolor;
            msgObj.style.position = "absolute";
            msgObj.style.left = "50%";
            msgObj.style.font="12px/1.6em Verdana, Geneva, Arial, Helvetica, sans-serif";

            msgObj.style.marginLeft = "-150px";

            msgObj.style.top = (document.body.scrollTop+200)+"px";
            msgObj.style.width = msgw + "px";
            msgObj.style.height = msgh + "px";
            msgObj.style.textAlign = "center";
            msgObj.style.lineHeight ="25px";
            msgObj.style.zIndex = "10001";
            document.body.appendChild(msgObj);

            var title=document.createElement("h4");
            title.setAttribute("id","alertmsgTitle");
            title.setAttribute("align","left");
            title.style.margin="0";
            title.style.padding="3px";
            title.style.background = bordercolor;
            title.style.filter="progid:DXImageTransform.Microsoft.Alpha(startX=20, startY=20, finishX=100, finishY=100,style=1,opacity=75,finishOpacity=100);";
            title.style.opacity="0.75";
            title.style.border="1px solid " + bordercolor;
            title.style.height="18px";
            title.style.font="12px Verdana, Geneva, Arial, Helvetica, sans-serif";
            title.style.color="white";
            title.innerHTML="提示信息";
            document.getElementById("alertmsgDiv").appendChild(title);

            var txt = document.createElement("p");
            txt.setAttribute("id","msgTxt");
            txt.style.margin="16px 0";
            txt.innerHTML = str;
            document.getElementById("alertmsgDiv").appendChild(txt);

            window.setTimeout("closewin()",500);
        }
        function closewin() {
            document.body.removeChild(document.getElementById("alertbgDiv"));
            document.getElementById("alertmsgDiv").removeChild(document.getElementById("alertmsgTitle"));
            document.body.removeChild(document.getElementById("alertmsgDiv"));
        }
var wz;
       gprdetail=0;
         function getdetail(){
            $("#tdbtn").empty();
            showmyaddr();
            $("#tdbtn").prepend('<button class="sui-btn btn-primary" onclick="showMsg(\'beiw-table\');">备忘</button>');
            QN.top.invoke({
                "cmd": "taobao.trade.fullinfo.get",
                "param":{
                    fields:'invoice_name,timeout_action_time,end_time,consign_time,buyer_rate,commission_fee,point_fee,buyer_cod_fee,real_point_fee,buyer_obtain_point_fee,yfx_fee,credit_card_fee,trade_memo,mark_desc,type,cod_status,seller_cod_fee,trade_from,buyer_alipay_no,promotion_details,seller_flag,seller_memo,end_time,seller_rate,status,seller_nick, buyer_nick,buyer_message,alipay_no,created,pay_time,end_time,payment,receiver_name,receiver_state,receiver_city,receiver_district,receiver_address,receiver_zip,receiver_mobile,orders.oid,receiver_phone,consign_time,shipping_type,orders,total_fee,orders,status,post_fee, created, tid, seller_rate,buyer_flag,adjust_fee',
                    tid:gtid
                },
                "method": "get",
                error: function(msp){
                /*请求出错处理 */
                /* alert(JSON.stringify(msp));*/
                if(typeof msp === 'string'){

                    var    msp = JSON.parse(msp);
                }else{
                    var	msp= msp;
                }
                if(msp.sub_code=='subuser.has-no-permission'){
                	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                    showMsg('hint');
                }else{
                    if(msp.sub_msg){
                    	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                        showMsg('hint');
                    }else{
                    	geterrorinfo('taobao.trade.fullinfo.get',msp);
                    }
                }
                },
                "success" : function(rsp) {
                    if(typeof rsp === 'string'){
                        var rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    if(rsp.code!=null){
                        if(520==rsp.code){
                        	$("#hints").html('<p>该订单是三个月前的订单，目前暂不提供查看信息！</p>');
                            showMsg('hint');
                        }else{
                            if(rsp.sub_msg){
                            	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                                showMsg('hint');
                            }else{
                            	geterrorinfo('taobao.trade.fullinfo.get',rsp);
                            }
                        }
                    }else{
                         var trade=rsp.trade_fullinfo_get_response.trade;   						
						if(trade.status=="TRADE_FINISHED" && trade.seller_rate==false){	/*交易成功，并且卖家木有评价勒！买家已收货，等待买家评论*/	
							debugger;
						typeinfo="后系统将自动好评！";
						var lasttime=gettimes(trade.end_time,15);
						SysSecond=datetime_to_unix(lasttime) - datetime_to_unix(taobaotime);	
						/*SysSecond=Math.abs(SysSecond);*/	
						/*SysSecond=parseInt(totime(trade.end_time,taobaotime,15));	*/					
							if(SysSecond>0){
								$("#gettimeinfo").html('正在奋力加载数据....');
	 							InterValObj = window.setInterval(SetRemainTime, 1000); /*间隔函数，1秒执行*/
							}else{$("#gettimeinfo").hide();} 													
					}else if(trade.status=="WAIT_BUYER_CONFIRM_GOODS"){/*卖家已发货，等待买家确认收货*/				
						if(trade.timeout_action_time!=undefined){
						typeinfo="后系统将自动确认收货！";
						SysSecond=datetime_to_unix(trade.timeout_action_time) - datetime_to_unix(taobaotime);	
						SysSecond=Math.abs(SysSecond);
						//SysSecond=parseInt(DateDiff(new Date(trade.timeout_action_time.replace(/-/g,"/")),new Date(taobaotime.replace(/-/g,"/"))));	/*获得两个时间的时间差*/
						if(SysSecond>0){
							$("#gettimeinfo").html('正在奋力加载数据....');
 							InterValObj = window.setInterval(SetRemainTime, 1000); 
						}else{$("#gettimeinfo").hide();} 	
						}else{$("#gettimeinfo").html('<h6><font color="red">拆单发货,不支持查看!</font></h6>');}							

					}else if(trade.status=="WAIT_BUYER_PAY"){		/*等待用户付款*/						
						typeinfo="后系统将自动关闭该订单！";		
						debugger;
						SysSecond=datetime_to_unix(trade.timeout_action_time) - datetime_to_unix(taobaotime);	
						SysSecond=Math.abs(SysSecond);	
						//SysSecond=parseInt(DateDiff(new Date(trade.timeout_action_time.replace(/-/g,"/")),new Date(taobaotime.replace(/-/g,"/"))));	/*获得两个时间的时间差*/
						if(SysSecond>0){
							$("#gettimeinfo").html('正在奋力加载数据....');
 							InterValObj = window.setInterval(SetRemainTime, 1000); 
						}else{$("#gettimeinfo").hide();} 																		
					}else{
						$("#gettimeinfo").hide();
					}		
                   	   	gtdsta = trade.status;
                        gname=trade.receiver_name;
                        gbuyernick=trade.buyer_nick;
                        gsellernick=trade.seller_nick;
                        gtime=trade.created;
                    var tsta='';
                    switch(gtdsta){
                        case 'TRADE_NO_CREATE_PAY':tsta='等待买家付款';$("#tdbtn").prepend('<button onclick="showMsg(\'close-table\');" class="sui-btn btn-primary">关闭订单</button>');showeditpost('NO'); break;
                        case 'WAIT_BUYER_PAY':tsta='等待买家付款';$("#tdbtn").prepend('<button class="sui-btn btn-primary" onclick="showMsg(\'close-table\');">关闭订单</button>');showeditpost('YES');break;
                        case 'WAIT_SELLER_SEND_GOODS':tsta='买家已付款,等待卖家发货'; if( trade.type=='cod'){if('NEW_CREATED'==trade.cod_status){$("#tdbtn").prepend('<button class="sui-btn btn-primary" onclick="showMsg(\'sendcoditem-table\')" >发货</button>');}tsta='买家已确认，等待卖家发货';}else{$("#tdbtn").prepend('<button class="sui-btn btn-primary" onclick="showMsg(\'senditem-table\');">发货</button>');}break;
                        case 'WAIT_BUYER_CONFIRM_GOODS':tsta='卖家已发货,等待买家确认'; break;
                        case 'SELLER_CONSIGNED_PART':tsta='卖家部分发货';$("#tdbtn").prepend('<button class="sui-btn btn-primary" onclick="showMsg(\'senditem-table\');">发货</button>');break;
                        case 'TRADE_BUYER_SIGNED':tsta='买家已签收 , 回款至卖家'; break;
                        case 'TRADE_FINISHED':tsta='交易成功'; break;
                        case 'TRADE_CLOSED':tsta='交易关闭';break;
                        case 'TRADE_CLOSED_BY_TAOBAO':tsta='交易关闭';break;

                    }                
                    $("#tdsta").html(tsta);
                    var bmessage='';
                    if(undefined!=trade.buyer_message){
                        bmessage=trade.buyer_message;                       
                        $("#buyercon").html('<p>买家留言：'+bmessage+'</p>');
                    }
                 var trade_from=trade.trade_from;
                     trade_from=trade_from.split(',');
                 var textval='';
                 for(var itxet in trade_from){
                    var text=''
                    switch(trade_from[itxet]){
                        case 'WAP':text='手机';break;
                        case 'HITAO':text='嗨淘';break;
                        case 'TOP':text='TOP平台';break;
                        case 'TAOBAO':text='普通淘宝';break;
                        case 'JHS':text='聚划算';break;
                        default :text='';break;
                    }
                     if(itxet<(trade_from.length-1)){
                        textval+=text+',';
                     }else{
                         textval+=text;
                     }
                 }
                        $("#tdbuy").html('<p>买家昵称：<a onclick=\"wangwang(\''+trade.buyer_nick+'\');\"  href=\"javascript:void(0);\"><img border=\"0\" src=\"http://amos.alicdn.com/realonline.aw?v=2&uid='+trade.buyer_nick+'&site=cntaobao&s=2&charset=utf-8\"/>'+trade.buyer_nick+'</a></p><p>买家支付宝：'+trade.buyer_alipay_no+'&nbsp;&nbsp;<a  href=\"#\" onclick=\"goalipay(\''+trade.seller_nick+'\',\''+trade.buyer_alipay_no+'\')\">付款给买家</a></p><p>订单来源：'+textval+'</p>');
                        var sellerf=false;
                        var Vflag="http://cdn.zzgdapp.com/trade/web/images/op_memo_0.png";
                    if(trade.seller_flag==0){
                        $(':radio[name="beiwf"]').eq(0).attr("checked",false);
                        $(':radio[name="beiwf"]').eq(1).attr("checked",false);
                        $(':radio[name="beiwf"]').eq(2).attr("checked",false);
                        $(':radio[name="beiwf"]').eq(3).attr("checked",false);
                        $(':radio[name="beiwf"]').eq(4).attr("checked",false);
                        if(undefined==trade.seller_memo){
                            gbeiwsta ='add';
                       $("#beiwtext").val('');
                        }else{
                            gbeiwsta ='eid';
                           $("#beiwtext").val(trade.seller_memo);
                            sellerf=true;
                        }
                    }
                    if(trade.seller_flag==1){
                        $(':radio[name="beiwf"]').eq(0).attr("checked",true);
                        gbeiwsta ='eid';
                      $("#beiwtext").val(trade.seller_memo);
                        sellerf=true;
                        Vflag="http://cdn.zzgdapp.com/trade/web/images/op_memo_1.png";
                    }
                    if(trade.seller_flag==2){
                        $(':radio[name="beiwf"]').eq(1).attr("checked",true);
                        gbeiwsta ='eid';
                       $("#beiwtext").val(trade.seller_memo);
                        sellerf=true;
                        Vflag="http://cdn.zzgdapp.com/trade/web/images/op_memo_2.png";
                    }
                    if(trade.seller_flag==3){
                        $(':radio[name="beiwf"]').eq(2).attr("checked",true);
                        gbeiwsta ='eid';
                        $("#beiwtext").val(trade.seller_memo);
                        sellerf=true;
                        Vflag="http://cdn.zzgdapp.com/trade/web/images/op_memo_3.png";
                    }
                    if(trade.seller_flag==4){
                        $(':radio[name="beiwf"]').eq(3).attr("checked",true);
                        gbeiwsta ='eid';
                        $("#beiwtext").val(trade.seller_memo);
                        sellerf=true;
                        Vflag="http://cdn.zzgdapp.com/trade/web/images/op_memo_4.png";
                    }
                    if(trade.seller_flag==5){
                        $(':radio[name="beiwf"]').eq(4).attr("checked",true);
                        gbeiwsta ='eid';
                       $("#beiwtext").val(trade.seller_memo);
                        sellerf=true;
                        Vflag="http://cdn.zzgdapp.com/trade/web/images/op_memo_5.png";
                    }
                    if(sellerf){
                        if(bmessage==''){
                            if(trade.seller_memo!=undefined){
                            	$("#buyercon").html('<p>卖家备注：<img src='+ Vflag +' />'+trade.seller_memo+'</p>');
                            }else{
                            	$("#buyercon").hide();
                                }
                        }else{
                            $("#buyercon").html('<p>卖家备注：<img src='+ Vflag +' />'+trade.seller_memo+'</p><p>买家留言：'+bmessage+'</p>');
                            $("#buyercon").show();
                        }
                        
                    }else{
                        if(bmessage!=''){
                            $("#buyercon").show();
                        }else{
                        	$("#buyercon").hide();
                        }
                    }
                      var datas= {};
                        if(sellerf){
                            datas.sendsmessage=trade.seller_memo;
                        }else{
                            datas.sendsmessage= '';
                        }	
	                datas.sendbmessage=bmessage;
                    datas.tid = trade.tid;
                    datas.alipay_no = trade.alipay_no;
                    datas.created = trade.created;
                    datas.pay_time = trade.pay_time;
                    datas.end_time = trade.end_time;
                    var source = $("#tdtid_template").html();
                    var template=Handlebars.compile(source);
                    var htmlstr = template(datas);
                    $("#tdtid").html(htmlstr).trigger('create');
						if('TRADE_FINISHED'==trade.status){
		                    if(datetime_to_unix(trade.end_time) > datetime_to_unix(GetDateStr(-15))&&trade.seller_rate==false){
		                        tsta= '待评价';
		                        $("#tdbtn").prepend('<button class="sui-btn btn-primary" onclick="showMsg(\'pingjia-table\');">评价</button>');
		                    }else{
		                        tsta= '已成功';
		                    }
						}
      				    datas.tditems=trade.orders.order;
                    	var value=datas.tditems.length;
                        gprdetail=0;
                        var tidptil='店铺优惠';
                        if(trade.promotion_details){
                        for(var pn in trade.promotion_details.promotion_detail){
                            var prdetail=trade.promotion_details.promotion_detail[pn];
                            if(trade.tid==prdetail.id){
                                if(1==trade.promotion_details.promotion_detail.length&&trade.orders.order[0].discount_fee!=0){
                                    gprdetail=0;
                                    break;

                                }else{
                                    gprdetail=prdetail.discount_fee;
                                    tidptil=prdetail.promotion_name;
                                    break;
                                }
                            }

                        }
                        }
                    datas.total_fee=trade.total_fee;
                    datas.post_fee=trade.post_fee;
                    window.gpost_fee= datas.post_fee;
                    window.gtotal_fee= datas.total_fee;
                    window.goidarr= new Array();
                    var tadjust_fee = 0;
                    var tdiscount_fee=0;
                    var refstall=true;
                    for(var n in trade.orders.order){
                        var oid=trade.orders.order[n].oid;
                        goidarr[n]=oid;
                        tadjust_fee =Number(tadjust_fee) + Number(trade.orders.order[n].adjust_fee);
                        tdiscount_fee =Number(tdiscount_fee) + Number(trade.orders.order[n].discount_fee);
                        var zhe=''
                        if(datas.adjust_fee-datas.discount_fee==0){
                            datas.tditems[n].zhe='';
                        }else{
                            zhe=parseFloat(trade.orders.order[n].price*trade.orders.order[n].num)+parseFloat(trade.orders.order[n].adjust_fee)-trade.orders.order[n].discount_fee;
                            zhe*=10;
                            var pn=trade.orders.order[n].price*trade.orders.order[n].num;
                            zhe/=pn;
                            datas.tditems[n].zhe=zhe.toFixed(2);
                        }
                        datas.tditems[n].zhe_fee=(parseFloat(trade.orders.order[n].adjust_fee)-parseFloat(trade.orders.order[n].discount_fee)).toFixed(2);
                        datas.tditems[n].itemtotal=pn.toFixed(2);
                        datas.tditems[n].tid= gtid;
                        if(trade.promotion_details){
                            for(var pn in trade.promotion_details.promotion_detail){
                                var prdetail=trade.promotion_details.promotion_detail[pn];
                                if(oid==prdetail.id){
                                    if(1==trade.promotion_details.promotion_detail.length){
                                        if(trade.orders.order[0].discount_fee!=0){
                                        datas.tditems[n].oidsptil=" "+prdetail.promotion_name+'：'+prdetail.discount_fee;
                                        break;
                                        }
                                    }else{
                                        datas.tditems[n].oidsptil=" "+prdetail.promotion_name+'：'+prdetail.discount_fee;
                                        break;
                                    }
                                }else{
                                    datas.tditems[n].oidsptil='';
                                }

                            }
                        }
                		if(trade.credit_card_fee!=undefined)
                			{
                				datas.tditems[n].iscardmoney=trade.credit_card_fee+"元";
                			}else {datas.tditems[n].iscardmoney="0.00元";}

                        if(datas.tditems[n].status=="WAIT_BUYER_CONFIRM_GOODS"){
                        	datas.tditems[n].iscdsend=false;
                        	value--;
                        }else{
                        	datas.tditems[n].iscdsend=true;
                        }
                        if(datas.tditems[n].status=="TRADE_NO_CREATE_PAY"||datas.tditems[n].status=="WAIT_BUYER_PAY"){
                        	datas.tditems[n].iscdclose=true;
                        }else{
                        	datas.tditems[n].iscdclose=false;
                        }

                        if(trade.orders.order[n].refund_id){
                            if(trade.orders.order[n].refund_status!='CLOSED'){
                            refstall=false;
                            }
                        }
                        if(trade.orders.order[n].refund_id){
                            datas.tditems[n].rurl='<?php echo APP_WEB_INDEX_ROOT?>/trade/refundinfo?vers=<?php echo REAL_ROOT_VER;?>#refundId='+trade.orders.order[n].refund_id;
                        }else{
                            datas.tditems[n].rurl='';
                        }
                        datas.outer_sku_id=trade.orders.order[n].outer_sku_id;
                        datas.outer_iid=trade.orders.order[n].outer_iid;
                    }
                    if(refstall){
                        if('WAIT_BUYER_CONFIRM_GOODS'==trade.status||'SELLER_CONSIGNED_PART'==trade.status){
                            $("#tdbtn").prepend('<button class="sui-btn btn-primary" onclick="showMsg(\'shtime-table\');">延长收货时间</button>');
                        }
                    }

                    if(value==datas.tditems.length){
			    		cdsend=value;
		    		}else{
			    		cdsend=0;
		    		}
                    datas.tadjust_fee = (Number(tadjust_fee)-Number(tdiscount_fee)).toFixed(2);

                     window.gtadjust_fee= datas.tadjust_fee;
                        datas.pricetotal= (Number(datas.tadjust_fee)+ Number(datas.total_fee)+Number(datas.post_fee)-Number(gprdetail)).toFixed(2);
                        if(datas.tadjust_fee<0){
                            if(0==gprdetail){
                                datas.maijiashifu='买家实付：'+datas.total_fee +' + '+ datas.post_fee +' '+ datas.tadjust_fee+' = '+datas.pricetotal;
                            }else{
                                datas.maijiashifu='买家实付：'+datas.total_fee +' + '+ datas.post_fee +' '+ datas.tadjust_fee+' - '+gprdetail+' = '+datas.pricetotal;
                            }
                        }else{
                            if(0==gprdetail){
                                datas.maijiashifu='买家实付：'+datas.total_fee +' + '+ datas.post_fee +' + '+datas.tadjust_fee+' = '+datas.pricetotal;
                            }else{
                                datas.maijiashifu='买家实付：'+datas.total_fee +' + '+ datas.post_fee +' + '+datas.tadjust_fee+' - '+gprdetail+' = '+datas.pricetotal;
                            }
                        }                        
                        var source = $("#closelist_template").html();
                        var template=Handlebars.compile(source);
                        var htmlstr = template(datas);
                        $("#closelist").html(htmlstr).trigger('create');
                        
                   		source = $("#tditem_template").html();                
                    	template=Handlebars.compile(source);
                    	htmlstr = template(datas);
                       	$("#tditem").html(htmlstr).trigger('create');
                    	var datas2={};
    					if(trade.yfx_fee!=undefined)/*运费险*/
    						{
    							datas2.yunfeixian=trade.yfx_fee+".00元";
    						}else {datas2.yunfeixian="0.00元 ";}

    					if(trade.commission_fee!="0.00")/*交易佣金*/
    						{
    							datas2.jiaoyimoney=trade.commission_fee+".00元";
    						}else{datas2.jiaoyimoney="0.00元";}

    					if(trade.point_fee!="0.00")/*买家使用积分*/
    					{
    						datas2.buerjifen=trade.point_fee+"个";
    					}else{datas2.buerjifen="0个";}						
	
    					if(trade.buyer_cod_fee!="0.00" || trade.seller_cod_fee!="0.00")/*货到付款费用*/    					
        				{    						
    						/*datas2.huodaomoney=parseInt(trade.payment)+parseInt(trade.buyer_cod_fee)+".00元";加上了货到付款的服务费*/
    						datas2.huodaomoney=trade.payment+"元";

        				}else{datas2.huodaomoney="0.00元";}

    					if(trade.real_point_fee!="0.00")/*实际使用积分*/
    					{
    						datas2.shijishiyongjifen=trade.real_point_fee+"个";
    					}else{datas2.shijishiyongjifen="0个";}

    					if(trade.buyer_obtain_point_fee!="0.00")/*买家获得积分*/
    					{
    						datas2.buyerGetjifen=trade.buyer_obtain_point_fee+"个";
    					}else{datas2.buyerGetjifen="0个";}
						if(trade.invoice_name!=undefined)
						{
							datas2.receipthead=trade.invoice_name;
						}else{
							datas2.receipthead="无";
						}
						source2 = $("#jifeninfo_template").html();     /*新定义的模版*/           
                     	template=Handlebars.compile(source2);
                      	htmlstr = template(datas2);
                        $("#infoitem").html(htmlstr).trigger('create');		
                        var paymenttext='';
                         var youhui=(Number(datas.total_fee)+Number(datas.post_fee))-Number(trade.payment);
							 
                         youhui=ForDight(youhui,2);
                        /* alert(youhui);*/
							if(youhui >= 0){
	                             paymenttext=datas.total_fee+'+'+datas.post_fee+'-'+youhui+'='+trade.payment+'元';
	                        }else{
		                        youhui=Math.abs(youhui);
	                            paymenttext=datas.total_fee+'+'+datas.post_fee+'+'+youhui+'='+trade.payment+'元';
	                        }
                       
                        if(0==gprdetail){						                 
                            $("#tdprice").html('<p style=\"text-align:right;\" >实收款：<span style=\"color:#f00;\" >'+paymenttext+'</span></p><p style=\"text-align:right;\" ><span style=\"color:gray;\" >实收款 = 原价 + 运费 + 涨价或折扣</span></p>').trigger('create');
                             }else{
                            $("#tdprice").html('<p style=\"text-align:right;\" >'+tidptil+'：'+gprdetail+'元</p><p style=\"text-align:right;\" >实收款：<span style=\"color:#f00;\" >'+paymenttext+'</span></p><p style=\"text-align:right;\" ><span style=\"color:gray;\" >实收款 = 原价 + 运费 + 涨价或折扣</span></p>').trigger('create');
                        }
                        if(undefined!=trade.seller_cod_fee&&'cod'==trade.type){
                            $("#codprice").html('<p style=\"text-align:right;\" >卖家承担服务费：'+trade.seller_cod_fee+'元</p>');
                        }else{
                            $("#codprice").html('');
                        }
                    datas.receiver_name= trade.receiver_name;
                    datas.receiver_state = trade.receiver_state;
                    datas.receiver_city = trade.receiver_city;
                    datas.receiver_district = trade.receiver_district;
                    gmoreshen= trade.receiver_state;
                    gmoreshi=trade.receiver_city;
                    gmorequ=trade.receiver_district;
                    datas.receiver_address = trade.receiver_address;
                    datas.receiver_zip = trade.receiver_zip;
                    datas.receiver_mobile = trade.receiver_mobile;
                    datas.receiver_phone = trade.receiver_phone;
                    datas.consign_time = trade.consign_time;
                    datas.shipping_type = '';
                    $("#more_zip").val(trade.receiver_zip);
                    $("#more_name").val(trade.receiver_name);
                    $("#more_address").val(trade.receiver_address);
                    $("#more_phone").val(trade.receiver_phone);
                    $("#more_mobile").val(trade.receiver_mobile);
                    /* 可选值：free(卖家包邮),post(平邮),express(快递),ems(EMS),virtual(虚拟发货)，25(次日必达)，26(预约配送)。
                     */
                    switch(trade.shipping_type){
                        case 'free': datas.shipping_type = '卖家包邮';break;
                        case 'post': datas.shipping_type = '平邮';break;
                        case 'express': datas.shipping_type = '快递';break;
                        case 'ems': datas.shipping_type = 'EMS';break;
                        case 'virtual': datas.shipping_type = '虚拟发货';break;
                        case '25': datas.shipping_type = '次日必达';break;
                        case '26': datas.shipping_type = '预约配送';break;
                    }
                    datas.buyer_nick=trade.buyer_nick;
                    datas.seller_nick=trade.seller_nick;
                    user_nick=datas.seller_nick;
                    datas.wlflase = true;
                    datas.wleditt = false;
                    var source = $("#pricebd_template").html();
                    var template=Handlebars.compile(source);
                    var htmlstr = template(datas);
                    $("#pricebody").html(htmlstr).trigger('create');

                    var source = $("#pingjiadata_template").html();
                    var template=Handlebars.compile(source);
                    var htmlstr = template(datas);
                    $("#pingjiadata").html(htmlstr).trigger('create');
                        getmymemo();
                        getmypjcon();
                    var source = $("#sendlist_template").html();
                    var template=Handlebars.compile(source);
                    var htmlstr = template(datas);
                    $("#sendlist").html(htmlstr).trigger('create');
                    $("#bfselect").hide();
                    if(gtdsta=='WAIT_BUYER_CONFIRM_GOODS'||gtdsta=='SELLER_CONSIGNED_PART'){
                    	wz='已发货';
                    }else{
                        wz='';
                    }
                    var source = $("#codsendlist_template").html();
                    var template=Handlebars.compile(source);
                    var htmlstr = template(datas);
                    $("#sendcodlist").html(htmlstr).trigger('create');	
                    if('WAIT_BUYER_PAY'==gtdsta||'TRADE_NO_CREATE_PAY'==gtdsta ||'WAIT_SELLER_SEND_GOODS'==gtdsta||'TRADE_CLOSED_BY_TAOBAO'==gtdsta||'TRADE_CLOSED'==gtdsta)
                    {
                        if('cod'==trade.type&&'NEW_CREATED'==trade.cod_status){
                            datas.company_name = '-';
                            datas.out_sid = '-';
                            datas.wlflase = false;
                            if('WAIT_SELLER_SEND_GOODS'==gtdsta){
                                datas.wleditt = true;
                            }
                            var source = $("#tdwuliu_template").html();
                            var template=Handlebars.compile(source);
                            var htmlstr = template(datas);
                            $("#tdwuliu").html(htmlstr).trigger('create');
                            getcompty(null);

                            $("#wltab").hide();
                        }else{
                            datas.company_name = '-';
                            datas.out_sid = '-';
                            datas.wlflase = false;
                            if('WAIT_SELLER_SEND_GOODS'==gtdsta){
                                datas.wleditt = true;
                            }
                            var source = $("#tdwuliu_template").html();
                            var template=Handlebars.compile(source);
                            var htmlstr = template(datas);
                            $("#tdwuliu").html(htmlstr).trigger('create');
                            $("#wltab").hide();
                            /*showwuliu(datas);*/
                        }
                    }else{

                        $("#wltab").show()
                        showwuliu(datas);
                    }
                	if('WAIT_SELLER_SEND_GOODS'==gtdsta||'SELLER_CONSIGNED_PART'==gtdsta){
                		getcompty(null);/*加载默认物流*/
                		$('#comptyid').change(c_offline);
                	}
                }
            }
            });


        }
         
         function ForDight(Dight,How){  /*四舍五入*/
             Dight = Math.round(Dight*Math.pow(10,How))/Math.pow(10,How);  
             return Dight;  
         }  
         function showmyaddr()/*显示我的发货地址*/
         {           	     
        	$("#selectaddrQ").empty();
           	$("#selectaddrW").empty();
           	$("#selectbackaddr").empty();
           	$("#selectbackaddrQ").empty();    	
        	 QN.top.invoke({
        		 "cmd": "taobao.logistics.address.search",
       		 "method": "get",
       		 "success": function(rsp){
       			 if(typeof  rsp=== 'string'){
       	            	rsp = JSON.parse(rsp);
       	            }
       			if(rsp.logistics_address_search_response){
       				    var datas={};
       				    window.ftdata={};
       	                for(index in rsp.logistics_address_search_response.addresses.address_result){
       	                     var result=rsp.logistics_address_search_response.addresses.address_result[index];
       	                    	datas.province=result.province;
                               	datas.city=result.city;
       	                   		datas.country=result.country;
       	                   		datas.addr=result.addr;
       	                   		datas.zip_code=result.zip_code;
       	                   		datas.contact_name=result.contact_name;
       	                   		datas.phone=result.phone;
       	                   		datas.mobile_phone=result.mobile_phone;
       	                   		datas.memo=result.memo;
       	                   		datas.seller_company=result.seller_company;
       	                   		datas.get_def=result.get_def;
       	                   		datas.cancel_def=result.cancel_def;  	                  
       	                    datas.contact_id=result.contact_id;
       	                    ftdata[index]=datas;
         	                 
         	                var source = $("#selectaddr_template").html();
         	                var template=Handlebars.compile(source);
       	  		   	        var htmlstr = template(datas);
       	  		   	        $("#selectaddrQ").append(htmlstr); 
       	   	  		   		$("#selectaddrW").append(htmlstr);   
	       	   	   	  		 source = $("#selectbackaddr_template").html();
	      	                 template=Handlebars.compile(source);
	       		   	      	 htmlstr = template(datas);       	   	   	  		
	     					 $("#selectbackaddr").append(htmlstr); 
	       	    	   	   	 $("#selectbackaddrQ").append(htmlstr);
	         			   	 datas={};  
       	          		  }
       			}
       	        },
       	        error: function(msp){
                       /*请求出错处理 */
                       /* alert(JSON.stringify(msp));*/
                       if(typeof msp === 'string'){
                           var msp = JSON.parse(msp);
                       }else{
                           var msp= msp;
                       }
                       if(msp.sub_code=='subuser.has-no-permission'){
                    	  $("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                           showMsg('hint');
                      }else{
                    	  geterrorinfo('taobao.logistics.address.search',msp);
                       }
                   }
       		 });
         
         }
    	var gdata={};
    	var mycd;
    	var mysub_tids;
		function showwuliu(mydatas){
		try{
			gdata=mydatas;
    		$("#bfselect").empty();
    		$("#tdwldatas").empty();
        	QN.top.invoke({
        		"cmd": "taobao.logistics.orders.get",
        		"param": {fields:'tid,order_code,seller_nick,buyer_nick,delivery_start,delivery_end,out_sid,item_title,receiver_name,created,modified,status,type,freight_payer,seller_confirm,company_name,sub_tids,is_spilt',tid:gtid},
        		"method": "get",
        		"success": function (rsp){
                    if(typeof  rsp=== 'string'){
                    	rsp = JSON.parse(rsp);
                    	} 
                    if(rsp.code!=null){
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                            showMsg('hint');
                        }else{
                        	$("#hints").html('<p>操作失败，请重试！</p>');
                            showMsg('hint');
                        }
                    }else{
                             var orders=rsp.logistics_orders_get_response.shippings.shipping;
                             var datas={};
                             var i=1;
                             var n=0;
                             for(index in orders){
	                                 var item=orders[index];
	          		    			if(datetime_to_unix(GetDateStr(0))-datetime_to_unix(item.created)>=23*60*60+50*60){
	        			    			/* var show_resend=false; */
	          		    				var show_resend=true;
	          		    				mydatas.edit_property=false;
	        		    			}else{
	        			    			var show_resend=true;
	        			    			mydatas.edit_property=true;
	        		    			}
	        		    			if(show_resend && item.company_name!= null && wz=='已发货'){
	        		    				mydatas.isresend=true;
	        		    			}else{
	        		    				mydatas.isresend=false;
	        		    			}
                             }
    
                             
                             if(orders.length<2){
                            	 $("#bfselect").hide();
                            	 showwulius(mydatas);
                             }else{
                            	 mycd=true;
                            	 $("#bfselect").show();
                                 var n=0;
                                 var i=1;
                           for(index in orders){
                                 var item=orders[index];
                                 if(item.seller_confirm=="yes"){
                    				 	$("#bfselect").append("<option value=\""+index+"\" >包裹"+i+"</option>").trigger("create");
										i++;
         	    	            		if(n==0){
         	 	    	            		n++;
        	                                 if(item.company_name!=null&&item.company_name!==''){
          	                                 	mydatas.company_name=item.company_name;
          	                                 }
          	                                 if(item.out_sid!=null&&item.out_sid!==''){
          	                                   	mydatas.out_sid=item.out_sid;
          	                                   }
          		          		    			if(datetime_to_unix(GetDateStr(0))-datetime_to_unix(item.created)>=23*60*60+50*60){
          		        			    			var show_resend=false;
          		
          		        		    			}else{
          		        			    			var show_resend=true;
          		        		    			}
          		        		    			if(show_resend&&item.company_name!=null&&wz=='已发货'){
          		        		    				mydatas.isresend=true;
          		        		    			}else{
          		        		    				mydatas.isresend=false;
          		        		    			}
          	       			                    var source = $("#tdwuliu_template").html();
          	       			                    var template=Handlebars.compile(source);
          	       			                    var htmlstr = template(mydatas);
          	       			                    $("#tdwuliu").html(htmlstr).trigger('create');
                  				 	datas.sub_tid=item.sub_tids.number;
                  				 	mysub_tids=datas.sub_tid;
                  				 	QN.top.invoke({
                  						"cmd": "taobao.logistics.trace.search",
                  						"param": {tid:gtid,seller_nick:user_nick,is_split:'1',sub_tid:datas.sub_tid},
                  						"method": "get",
                  						"success": function (rsp){
                  				            if(typeof  rsp=== 'string'){
                  				            	rsp = JSON.parse(rsp);
                  				            }
                  				            if(rsp.code!=null){
                                                if(rsp.sub_msg){
                                                	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                                                    showMsg('hint');
                                                }else{
                                                	$("#hints").html('<p>操作失败，请重试！</p>');
                                                    showMsg('hint');
                                                }
                  				            }else{
                 				            	 var datas= {};
                 				            	 
                   			                    mydatas.company_name = rsp.logistics_trace_search_response.company_name;
                   			                    mydatas.out_sid = rsp.logistics_trace_search_response.out_sid;
                   			                    datas.tracelists = rsp.logistics_trace_search_response.trace_list.transit_step_info;
                   			                    var source = $("#tdwldatas_template").html();
                   			                    var template=Handlebars.compile(source);
                   			                    var htmlstr = template(datas);
                   			                    $("#tdwldatas").html(htmlstr).trigger('create');
                  				            }
                  					    		}
                  							}
                  					);
                                 }
                                 }

              				 	
                             }
                         }
        		} 
        		},
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                     	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                        showMsg('hint');
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                            showMsg('hint');
                        }else{
                       	 	geterrorinfo('taobao.logistics.orders.get',msp);
                        }
                    }

                }
        	 });
		}catch(e){
		}
    }

function showbg(){
	var sel=$("#bfselect").find("option:selected").val();
	$("#tdwldatas").empty();
	QN.top.invoke({
		"cmd": "taobao.logistics.orders.get",
		"param": {fields:'tid,order_code,seller_nick,buyer_nick,delivery_start,delivery_end,out_sid,item_title,receiver_name,created,modified,status,type,freight_payer,seller_confirm,company_name,sub_tids,is_spilt',tid:gtid},
		"method": "get",
		"success": function (rsp){
            if(typeof  rsp=== 'string'){
            	rsp = JSON.parse(rsp);
            }                
            if(rsp.code!=null){
                if(rsp.sub_msg){
                	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                    showMsg('hint');
                }else{
                	$("#hints").html('<p>操作失败，请重试！</p>');
                    showMsg('hint');
                }
            }else{
                     var orders=rsp.logistics_orders_get_response.shippings.shipping;
                     var datas={};
                     for(index in orders){
                         var item=orders[index];
                         if(index==sel){
                             if(item.company_name!=null&&item.company_name!==''){
                             	gdata.company_name=item.company_name;
                             }
                             if(item.out_sid!=null&&item.out_sid!==''){
                               	gdata.out_sid=item.out_sid;
                               }
	          		    			if(datetime_to_unix(GetDateStr(0))-datetime_to_unix(item.created)>=23*60*60+50*60){
	        			    			var show_resend=false;
	        		    			}else{
	        			    			var show_resend=true;
	        		    			}
	        		    			if(show_resend&&item.company_name!=null&&wz=='已发货'){
	        		    				gdata.isresend=true;
	        		    			}else{
	        		    				gdata.isresend=false;
	        		    			}
   			                    var source = $("#tdwuliu_template").html();
   			                    var template=Handlebars.compile(source);
   			                    var htmlstr = template(gdata);
   			                    $("#tdwuliu").html(htmlstr).trigger('create');
            				 	datas.sub_tid=item.sub_tids.number;
            				 	mysub_tids=datas.sub_tid;
            				 	QN.top.invoke({
            						"cmd": "taobao.logistics.trace.search",
            						"param": {tid:gtid,seller_nick:user_nick,is_split:'1',sub_tid:datas.sub_tid},
            						"method": "get",
            						"success": function (rsp){
            				            if(typeof  rsp=== 'string'){
            				            	rsp = JSON.parse(rsp);
            				            }
            				            if(rsp.code!=null){
            				            	$("#hints").html('<p>'+JSON.stringify(rsp)+'</p>');
            				            	showMsg('hint');
            				            }else{
           				            	 var datas= {};
             			                    gdata.company_name = rsp.logistics_trace_search_response.company_name;
             			                    gdata.out_sid = rsp.logistics_trace_search_response.out_sid;
             			                    datas.tracelists = rsp.logistics_trace_search_response.trace_list.transit_step_info;
             			                    var source = $("#tdwldatas_template").html();
             			                    var template=Handlebars.compile(source);
             			                    var htmlstr = template(datas);
             			                    $("#tdwldatas").html(htmlstr).trigger('create');
            				            }
            					    		}
            							}
            					);
                           }
                     }
			}
		},
        error: function(msp){
            if(typeof msp === 'string'){
                var msp = JSON.parse(msp);
            }else{
                var	msp= msp;
            }
            if(msp.sub_code=='subuser.has-no-permission'){
            	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
            	showMsg('hint');
            }else{
                if(msp.sub_msg){
                	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                	showMsg('hint');
                }else{
                	geterrorinfo('taobao.logistics.orders.get',msp);
                }
            }
        }
	 });
}
        function showwulius(datas)
        {
            QN.top.invoke({
                "cmd": "taobao.logistics.trace.search",
                "param":{
                    tid:gtid,
                    seller_nick:datas.seller_nick
                },
                "method": "get",
                "success" : function(rsp) {
                    if(typeof rsp === 'string'){
                        var rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    datas.company_name = rsp.logistics_trace_search_response.company_name;
                    datas.out_sid = rsp.logistics_trace_search_response.out_sid;
                    var source = $("#tdwuliu_template").html();
                    var template=Handlebars.compile(source);
                    var htmlstr = template(datas);
                    $("#tdwuliu").html(htmlstr).trigger('create');
                    datas.tracelists = rsp.logistics_trace_search_response.trace_list.transit_step_info;
                    var source = $("#tdwldatas_template").html();
                    var template=Handlebars.compile(source);
                    var htmlstr = template(datas);
                    $("#tdwldatas").html(htmlstr).trigger('create');
                },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                    	showMsg('hint'); 
                    }else{
                        if(msp.sub_msg){
                        	if(msp.sub_msg=="物流公司不支持流转查询")
							{
								datas.company_name = "亲！物流公司不支持流转查询哦。";
			                    datas.out_sid = false;
			                    var source = $("#tdwuliu_template").html();
			                    var template=Handlebars.compile(source);
			                    var htmlstr = template(datas);
			                    $("#tdwuliu").html(htmlstr).trigger('create');
			                    datas.tracelists = "亲！物流公司不支持流转查询哦。";
			                    datas.wuliuinfo="暂无物流信息！"
			                    var source = $("#tdwldatas_template").html();
			                    var template=Handlebars.compile(source);
			                    var htmlstr = template(datas);
			                    $("#tdwldatas").html(htmlstr).trigger('create');	
							}else{ 
								$("#hints").html('<p>'+msp.sub_msg+'</p>');
	                        	showMsg('hint');
							}
                        }else{
                        	geterrorinfo('taobao.logistics.trace.search',msp);
                        }
                    }

                }
            });
        }

function toresend(company){
	QN.top.invoke({
		"cmd": "taobao.logistics.companies.get",
		"param": {fields:'code,name',is_recommended:true,order_mode:'online'},
		"method": "get",
		"success": function (rsp){
	        if(typeof  rsp=== 'string'){
	        	rsp = JSON.parse(rsp);
	        }
	        if(rsp.code!=null){
                if(rsp.sub_msg){
                	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                	showMsg('hint');
                }else{
                	$("#hints").html('<p>操作失败，请重试！</p>');
                	showMsg('hint');
                }
	        }else{
	    			$('#resendlist').empty();
	    			var datas={};
	    			 for(index in rsp.logistics_companies_get_response.logistics_companies.logistics_company){
		    			 var order=rsp.logistics_companies_get_response.logistics_companies.logistics_company[index];
		    			 datas.name=order.name;
		    			 datas.code=order.code;
		    			 var source = $("#ontrade_template").html();
		    	            var template = Handlebars.compile(source);
		    	            var htmlstr = template(datas);
		    	            $("#resendlist").append(htmlstr);
		    	           		if(datas.name==company){
		    	            		$("#resendlist option[value='"+datas.code+"']").attr("selected","selected");
		    	            	}
	    			 }
	        }
	    	},
        error: function(msp){
            if(typeof msp === 'string'){
                var msp = JSON.parse(msp);
            }else{
                var	msp= msp;
            }
            if(msp.sub_code=='subuser.has-no-permission'){
            	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
            	showMsg('hint');
            }else{
                if(msp.sub_msg){
                	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                	showMsg('hint');
                }else{
                	geterrorinfo('taobao.logistics.companies.get',msp);
                }
            }

        }
	});
	showMsg('resend-table');
}
function toresends(){
	closeMsg('');
	var outid=$('#outid').val();
	var cycode=$('#resendlist').find("option:selected").val();
	if(outid==''){
		$("#hints").html('<p>修改发货失败,运单号不能为空！</p>');
    	showMsg('hint');
    	$("input[msgstu='again']").attr("onclick","closeMsg('resend-table');");
	}else{
		if(mycd==true){ /*拆单发货*/
			QN.top.invoke({
				"cmd": "taobao.logistics.consign.resend",
				"param": {tid:gtid,out_sid:outid,is_split:'1',sub_tid:mysub_tids,company_code:cycode,},
				"method": "get",
				"success": function (rsp){
		            if(typeof  rsp=== 'string'){
		            	rsp = JSON.parse(rsp);
		            }
	                if(rsp.code!=null){
	                	$('#outid').val(null);
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                        	showMsg('hint');
                        }else{
                        	$("#hints").html('<p>操作失败，请重试！</p>');
                        	showMsg('hint');
                        }
	                }else{
						$('#outid').val(null);
						showwuliu(gdata);
						$("#hints").html('<p>操作成功！</p>');
                    	showMsg('hint');
	                }
	            },
                error: function(msp){
                    /*请求出错处理 */
                    /* alert(JSON.stringify(msp));*/
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                    	showMsg('hint');
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                        	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.logistics.consign.resend',msp);
                        }
                    }

                }
	                   		       	
		 });
		}else{
			QN.top.invoke({
				"cmd": "taobao.logistics.consign.resend",
				"param": {tid:gtid,out_sid:outid,company_code:cycode},
				"method": "get",
				"success": function (rsp){
		            if(typeof  rsp=== 'string'){
		            	rsp = JSON.parse(rsp);
		            }
	                if(rsp.code!=null){
	                	$('#outid').val(null);
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                        	showMsg('hint');
                        }else{
                        	$("#hints").html('<p>操作失败，请重试！</p>');
                        	showMsg('hint');
                        }
	                }else{
						$('#outid').val(null);
						showwuliu(gdata);
						$("#hints").html('<p>操作成功！</p>');
                    	showMsg('hint');
	                }
	            },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                    	showMsg('hint');
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                        	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.logistics.consign.resend',msp);
                        }
                    }

                }
	                   		       	
		 });
		}
	}
}


        function addbeiw()
        {
        	closeMsg('');
            var data=$("#beiwtext").val();
            if(data.length>500){
            	$("#hints").html('<p>留言不能超过500字！</p>');
            	showMsg('hint');
            	$("input[msgstu='again']").attr("onclick","closeMsg('beiw-table');");
            }else{
            var seltitle=$(':radio[name="beiwf"]:checked').val();
       if(''==data){
    	    $("#hints").html('<p>备注内容不能为空！</p>');
          	showMsg('hint');
          	$("input[msgstu='again']").attr("onclick","closeMsg('beiw-table');");
        }else{
        if('add'==gbeiwsta){
            QN.top.invoke({
                "cmd": "taobao.trade.memo.add",
                "param":{
                    tid:gtid,
                    memo:data,
                    flag:seltitle
                },
                "method": "get",
                "success" : function(rsp) {
                    if(typeof rsp === 'string'){
                        var rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    var rsperror=rsp.msg;
                    if(rsperror==undefined){
                    	$("#hints").html('<p>添加成功！</p>');
                      	showMsg('hint');
                        getdetail();
                    }else{
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.memo.add',rsp);
                        }
                    }
                },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                      	showMsg('hint');
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.memo.add',msp);
                        }
                    }

                }
            });
        }else if('eid'==gbeiwsta){
                QN.top.invoke({
                    "cmd": "taobao.trade.memo.update",
                    "param":{
                        tid:gtid,
                        memo:data,
                        flag:seltitle
                    },
                    "method": "get",
                    "success" : function(rsp) {
                        if(typeof rsp === 'string'){
                            var rsp = JSON.parse(rsp);
                        }else{
                            var	rsp= rsp;
                        }
                        var rsperror=rsp.msg;
                        if(rsperror==undefined){
                        	$("#hints").html('<p>修改成功！</p>');
                          	showMsg('hint');
                            getdetail();
                        }else{
                            if(rsp.sub_msg){
                            	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                              	showMsg('hint');
                            }else{
                            	geterrorinfo('taobao.trade.memo.update',rsp);
                            }
                        }
                    },
                    error: function(msp){
                        if(typeof msp === 'string'){
                            var msp = JSON.parse(msp);
                        }else{
                            var	msp= msp;
                        }
                        if(msp.sub_code=='subuser.has-no-permission'){
                        	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                          	showMsg('hint');
                        }else{
                            if(msp.sub_msg){
                            	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                              	showMsg('hint');
                            }else{
                            	geterrorinfo('taobao.trade.memo.update',msp);
                            }
                        }

                    }
                });
        }else{
        	$("#hints").html('<p>gbeiwsta【'+gbeiwsta+'】</p>');
          	showMsg('hint');
        }
       }
       }
       }

        function pingjia()
        {
        	closeMsg('');
            var tql='';
            var pjtqlcom=false;
            var pjtextmax=false;
            for(var n in goidarr){
                var oid=goidarr[n];
                var mychecked =$(':radio[name="rate'+oid+'"]:checked').val();
                var text = $('#trate'+oid).val();
                if(text==''&&mychecked=='good'){
                    text='好评！';
                }
                if(text==''){
                    pjtqlcom=true;
                }
                if(text.length>500){
                    pjtextmax=true;
                }
                tql=tql+'{insert into traderate (tid,oid,result,role,content,anony) values ('+gtid+','+oid+','+mychecked+',seller,'+text+',false)}';
            }
            if(pjtextmax){
            	$("#hints").html('<p>评价内容不能超过500字！</p>');
              	showMsg('hint');
              	$("input[msgstu='again']").attr("onclick","closeMsg('pingjia-table');");
            }else if(pjtqlcom){
            	$("#hints").html('<p>中差评时评价内容不能为空！</p>');
              	showMsg('hint');
              	$("input[msgstu='again']").attr("onclick","closeMsg('pingjia-table');");
            }else{
            QN.top.invoke({
                "cmd":"tql",
                "param":{"ql":tql},
                "method":"post",
                "success":function (rsp){
                    if(typeof rsp === 'string'){
                        var rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    if(rsp[0].error_response){
                        if(rsp[0].error_response.sub_code=='subuser.has-no-permission'){
                        	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                          	showMsg('hint');
                        }else{
                            if(rsp.sub_msg){
                            	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                              	showMsg('hint');
                            }else{
                            	geterrorinfo('tql',rsp);
                            }
                        }
                    }else{
                    	$("#hints").html('<p>评价成功！</p>');
                      	showMsg('hint');
                    }
                },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                      	showMsg('hint'); 
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('tql',msp);
                        }
                    }

                }
            });
            }
        }
        /**
         * 关闭订单
         * 1.判断是否拆单关闭
         * @author Duanhq
         */
        function tidclose(){
        	var num=0;
        	var tids=new Array();
        	var turn=document.getElementsByName('closecheckcheckbox');
        	for(i=0;i<turn.length;i++){ 
        		if(turn[i].checked){ 
        			tids[num++]=turn[i].value;
        		}
        	}
            if(num==0){
            	closeMsg('');
            	$("#hints").html('<p>关闭错误，请选择需要关闭的订单！</p>');
                showMsg('hint');
                $("input[msgstu='again']").attr("onclick","closeMsg('close-table');");
        		
            }else{
        		if(num==turn.length){
        			/*不拆单关闭*/
        			tids=new Array([gtid]);
        		}
        		tidcloses(tids);
            }
            
        }
        /**
         * 关闭订单
         * 2.确认关闭
         * @aothor Duanhq
         */
        function tidcloses(closeid)
        {
        	closeMsg('');
            var day=$("#tidclose").val();
            if('0'!=day){
            	for(index in closeid){
                    QN.top.invoke({
                        "cmd": "taobao.trade.close",
                        "param":{
                            tid:''+closeid[index],
                            close_reason:day
                        },
                        "method": "get",
                        "success" : function(rsp) {
                            if(typeof rsp === 'string'){
                                var rsp = JSON.parse(rsp);
                            }else{
                                var	rsp= rsp;
                            }
                            var rsperror=rsp.msg;
                            if(rsperror==undefined){
                            	$("#hints").html('<p>操作成功！</p>');
                              	showMsg('hint');
                                getdetail();
                            }else{
                                if(rsp.sub_msg){
                                	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                                  	showMsg('hint');
                                }else{
                                	geterrorinfo('taobao.trade.close',rsp);
                                }
                            }
                        },
                        error: function(msp){
                            if(typeof msp === 'string'){
                                var msp = JSON.parse(msp);
                            }else{
                                var	msp= msp;
                            }
                            if(msp.sub_code=='subuser.has-no-permission'){
                             	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                              	showMsg('hint');
                            }else{
                                if(msp.sub_msg){
                                	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                                  	showMsg('hint');
                                }else{
                                	geterrorinfo('taobao.trade.close',msp);
                                }
                            }
                        }
                    });
            	}
            }else{
            	$("#hints").html('<p>关闭错误，关闭理由不能为空！</p>');
                showMsg('hint');
                $("input[msgstu='again']").attr("onclick","closeMsg('close-table');");
            }
        }
        function shaddtime()/*延长收货*/
        {
        	closeMsg('');
            var day=$("#shday").val();            
            QN.top.invoke({
                    "cmd": "taobao.trade.receivetime.delay",
                    "param":{
                        tid:gtid,
                        days:day
                    },
                    "method": "get",
                    "success" : function(rsp) {
                        if(typeof rsp === 'string'){
                            var rsp = JSON.parse(rsp);
                        }else{
                            var	rsp= rsp;
                        }
                        var rsperror=rsp.msg;
                        if(rsperror==undefined){
                        	$("#hints").html('<p>修改成功！</p>');
                            showMsg('hint');                        	
                            getdetail();
                        }else{
                            if(rsp.sub_msg){
                            	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                                showMsg('hint'); 
                            }else{
                            	geterrorinfo('taobao.trade.receivetime.delay',rsp);
                            }
                        }
                    },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                        showMsg('hint');
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                            showMsg('hint'); 
                        }else{
                        	geterrorinfo('taobao.trade.receivetime.delay',msp);
                        }
                    }

                }
                });

        }
    /*     改价组件           */
    function getpricer(){
        QN.top.invoke({
            "cmd": "taobao.user.seller.get",
            "param":{
                fields:'nick,type'
            },
            "method": "get",
            "success" : function(rsp) {
                if(typeof rsp === 'string'){
                    var rsp = JSON.parse(rsp);
                }else{
                    var	rsp= rsp;
                }
                QN.application.invoke({
                    "cmd": "getVersion",
                    "error" : function(msg) {
                        getdetail();
                        window.ggtadjust_fee ='';
                        showMsg('price-table');
                    },
                    "success" : function(e) {
                        if(typeof  e=== 'string'){
                            e = JSON.parse(e);
                        }
                        var version=e.version.replace(/[.]/g,"");
                        version=version.replace(/[N]/g,"");
                        if(version<10010){
                            getdetail();
                            window.ggtadjust_fee ='';
                            showMsg('price-table');
                        }else{
                            if(rsp.user_seller_get_response.user.type=='B'){
                                getdetail();
                                window.ggtadjust_fee ='';
                                showMsg('price-table');
                            }else{
                                try{
                                    QN.component.invoke( {
                                        category:'updateprice',
                                        param:{
                                            uuid:'2314',
                                            tid:gtid
                                        },
                                        error : function(msg, cmd, param) {

                                        },
                                        success : function(rsp, cmd, param) {
                                        	$("#hints").html('<p>改价成功！</p>');
                                          	showMsg('hint');
                                            getdetail();
                                        }
                                    });
                                }catch(e){
                                    getdetail();
                                    window.ggtadjust_fee ='';
                                    showMsg('price-table');
                                }

                            }

                        }
                    }

                    });
            },
            error: function(msp){
                if(typeof msp === 'string'){
                    var msp = JSON.parse(msp);
                }else{
                    var	msp= msp;
                }
                if(msp.sub_code=='subuser.has-no-permission'){
                	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                  	showMsg('hint');
                }else{
                    if(msp.sub_msg){
                    	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                      	showMsg('hint');
                    }else{
                    	geterrorinfo('改价组件',msp);
                    }
                }

            }
        });
    }
        function editprice()
        {
        	closeMsg('');
            var oids='';
            var fess='';
            var postfee= $("#postval").val();
            for(var i=0;i<goidarr.length;i++){
                oids+=goidarr[i];
                fess+=$("#slider-"+goidarr[i]).val();
                if(i<goidarr.length-1){
                    oids+=',';
                    fess+=',';
                }
            }
            QN.top.invoke({
                "cmd": "taobao.trade.price.update",
                "param":{
                    tid:gtid,
                    oids:oids,
                    adjust_fees:fess,
                    postage_fee:postfee
                },
                "method": "get",
                "success" : function(rsp) {
                    if(typeof rsp === 'string'){
                        var rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    var rsperror=rsp.msg;
                    if(rsperror==undefined){
                    	$("#hints").html('<p>修改成功！</p>');
                      	showMsg('hint');
                        getdetail();
                    }else{
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.price.update',rsp);
                        }
                    }
                },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                      	showMsg('hint');
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.price.update',msp);
                        }
                    }
                }
            });
        }
    /**催付****/
    function wwfastpay(){
    	tradePoint(user_nick,'详情催付按钮');
        if(vipuser==0){
          	showMsg('buyvip');
          	return;
        }
    	var cuifucontent=window.localStorage.getItem("cuifucontent"+user_nick);
		if(cuifucontent==''|| cuifucontent==null){
			$.ajax({
     		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/fastpay',
     		    type: 'POST',
     		    dataType:'html',
     		    data:{nick:user_nick},
     		    timeout:10000,
	            success: function(data){
	            	window.localStorage.setItem("cuifucontent"+user_nick,data);
	                data=data.replace(/<买家姓名>/g, gname);
	                data=data.replace(/<卖家旺旺>/g, gsellernick);
	                data=data.replace(/<订单链接>/g, 'http://trade.taobao.com/trade/detail/trade_item_detail.htm?bizOrderId='+gtid);
	                data=data.replace(/<买家旺旺>/g, gbuyernick);
	                data=data.replace(/<订单编号>/g, gtid);
	                data=data.replace(/<下单时间>/g, gtime);
	                wangwangPC(gbuyernick,data);
	            },
	            error: function(){
	                $("#hints").html('<p>操作失败，请重试！</p>');
                  	showMsg('hint');
	            }
	        });
		}else{
			cuifucontent=cuifucontent.replace(/<买家姓名>/g, gname);
			cuifucontent=cuifucontent.replace(/<卖家旺旺>/g, gsellernick);
			cuifucontent=cuifucontent.replace(/<订单链接>/g, 'http://trade.taobao.com/trade/detail/trade_item_detail.htm?bizOrderId='+gtid);
			cuifucontent=cuifucontent.replace(/<买家旺旺>/g, gbuyernick);
			cuifucontent=cuifucontent.replace(/<订单编号>/g, gtid);
			cuifucontent=cuifucontent.replace(/<下单时间>/g, gtime);
            wangwangPC(gbuyernick,cuifucontent);
			}
    }

    function showeditpost(created){
        QN.top.invoke({
            "cmd": "taobao.user.seller.get",
            "param":{
                fields:'nick,type'
            },
            "method": "get",
            "success" : function(rsp) {
                if(typeof rsp === 'string'){
                    var rsp = JSON.parse(rsp);
                }else{
                    var	rsp= rsp;
                }
                if(rsp.user_seller_get_response){
                    if(rsp.user_seller_get_response.user.type=='B'){
                        if(created=='YES'){
                        	$("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" onclick="showposttable();" data-toggle="modal"><button class="sui-btn btn-primary">改运费</button></a>');
                        }else {
                        	$("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" title ="由于买家没有绑定支付宝，您暂时无法为其修改运费，请提醒买家先绑定支付宝账户。" data-toggle="modal"><button class="sui-btn sui-btn-primary">改运费</button></a>');
                        }
                       $("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" onclick="wwfastpay();" data-toggle="modal"><button class="sui-btn btn-primary" title="点击发送到旺旺聊天窗口，您可在设置里添加自定催付内容哦！">催付</button></a>');
                    }else{
                        if(created=='YES'){
                        	$("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" onclick="getpricer();" data-toggle="modal"><button class="sui-btn btn-primary">改价</button></a>');
                        }else{
                        	$("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" title ="由于买家没有绑定支付宝，您暂时无法为其改价，请提醒买家先绑定支付宝账户。" data-toggle="modal"><button class="sui-btn btn-primary">改价</button></a>');
                        }
                        $("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" onclick="wwfastpay();" data-toggle="modal"><button class="sui-btn btn-primary" title="点击发送到旺旺聊天窗口，您可在设置里添加自定催付内容哦！">催付</button></a>');
                    }
                }else{
                	if(created=='YES'){
                    	$("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" onclick="getpricer();" data-toggle="modal"><button class="sui-btn btn-primary">改价</button></a>');
                    }else{
                    	$("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" title ="由于买家没有绑定支付宝，您暂时无法为其改价，请提醒买家先绑定支付宝账户。" data-toggle="modal"><button class="sui-btn btn-primary">改价</button></a>');
                    }
                    $("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" onclick="wwfastpay();" data-toggle="modal"><button class="sui-btn btn-primary" title="点击发送到旺旺聊天窗口，您可在设置里添加自定催付内容哦！">催付</button></a>');
                }
            },
            error: function(msp){
            	if(created=='YES'){
                	$("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" onclick="getpricer();" data-toggle="modal"><button class="sui-btn btn-primary">改价</button></a>');
                }else{
                	$("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" title ="由于买家没有绑定支付宝，您暂时无法为其改价，请提醒买家先绑定支付宝账户。" data-toggle="modal"><button class="sui-btn btn-primary">改价</button></a>');
                }
                $("#tdbtn").prepend('&nbsp<a href="javascript:void(0);" onclick="wwfastpay();" data-toggle="modal"><button class="sui-btn btn-primary" title="点击发送到旺旺聊天窗口，您可在设置里添加自定催付内容哦！">催付</button></a>');
            }
        });
    }
    function showposttable(){
        $("#editpostval").val('');
        showMsg('editpost-table');
    }
    function editpost(){
    	closeMsg('');
        var fee=$("#editpostval").val();
        fee=clearBr(fee);
        if(fee!=''){
            QN.top.invoke({
                "cmd": "taobao.trade.postage.update",
                "param":{
                    tid:gtid,
                    post_fee:fee
                },
                "method": "get",
                "success" : function(rsp) {
                    if(typeof rsp === 'string'){

                        var    rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    var rsperror=rsp.msg;
                    if(rsperror==undefined){
                    	$("#hints").html('<p>修改成功！</p>');
                      	showMsg('hint');
                        getdetail();
                    }else{
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>editpost:'+rsp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.postage.update',rsp);
                        }
                    }
                },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                      	showMsg('hint');
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>editpost2:'+msp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.postage.update',msp);
                        }
                    }
                }
            });
        }else{
        	$("#hints").html('<p>邮费不能为空！</p>');
          	showMsg('hint');
          	$("input[msgstu='again']").attr("onclick","closeMsg('editpost-table');");
        }
    }
        /*改邮费*/
        function postfree()
        {
            QN.top.invoke({
                "cmd": "taobao.trade.postage.update",
                "param":{
                    tid:gtid,
                    post_fee:0
                },
                "method": "get",
                "success" : function(rsp) {
                    if(typeof rsp === 'string'){
                        var rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    var rsperror=rsp.msg;
                    if(rsperror==undefined){
                    	$("#hints").html('<p>修改成功！</p>');
                      	showMsg('hint');
                        getdetail();
                    }else{
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.postage.update',rsp);
                        }
                    }
                },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                      	showMsg('hint');
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.postage.update',msp);
                        }
                    }

                }
            });
        }
        function twopostfree()
        {
            $("#postval").val('0');
            changepost();

        }
        function loadaddress()
        {
       	 var areadata = window.localStorage.getItem("areadata");
		 if(areadata=="null"||areadata==null){
			 $.ajax({
	     		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/getArea',
	     		    type: 'POST',
	     		    dataType:'html',
	     		    data:{},
	     		    timeout:10000,
	                success: function(datas){
	                	window.localStorage.setItem("areadata",datas);
	                    loaddata();
	                }
            });
		 }else{
			 loaddata();
			 }

        }
        function loaddata(){
        	var areadata = window.localStorage.getItem("areadata");
            $("#more_shen").empty();
            $("#more_shi").empty();
            $("#more_qu").empty();
            var object = eval("(" + areadata + ")");
            var provinces = object['province'];

            var procode ='';
            for(var i=0;i<provinces.length;i++)
            {
                if(provinces[i]['address']==gmoreshen)
                {   procode = provinces[i]['addcode'];
                    $("#more_shen").append("<option selected='selected' value='"+provinces[i]['addcode']+","+provinces[i]['address']+"'>"+provinces[i]['address']+"</option>");
                }else{
                    $("#more_shen").append("<option  value='"+provinces[i]['addcode']+","+provinces[i]['address']+"'>"+provinces[i]['address']+"</option>");
                }
            }

            var citys = object['citys'][procode];
            var citycode = '';
            for(var i=0;i<citys.length;i++)
            {
                if(citys[i]['address']== gmoreshi)
                {   citycode = citys[i]['addcode'];
                    $("#more_shi").append("<option selected='selected' value='"+citys[i]['addcode']+","+citys[i]['address']+"'>"+citys[i]['address']+"</option>");
                }else{
                    $("#more_shi").append("<option  value='"+citys[i]['addcode']+","+citys[i]['address']+"'>"+citys[i]['address']+"</option>");
                }
            }
            var districts = object['districts'][citycode];
            for(var i=0;i<districts.length;i++)
            {
                if(districts[i]['address']==gmorequ)
                {
                    $("#more_qu").append("<option selected='selected' value='"+districts[i]['addcode']+","+districts[i]['address']+"'>"+districts[i]['address']+"</option>");
                }else{
                    $("#more_qu").append("<option  value='"+districts[i]['addcode']+","+districts[i]['address']+"'>"+districts[i]['address']+"</option>");
                }
            }
            $("#more_shen").trigger("create");
            $("#more_shi").trigger("create");
            $("#more_qu").trigger("create");
            $("#more_shen").change(p_choice);
            $("#more_shi").change(c_choice);
        }
        function p_choice()
        {
        	var areadata = window.localStorage.getItem("areadata");
            var sel= $("#more_shen").find('option:selected').val();
            if(areadata!=null)
            {
                var object = eval("(" + areadata+ ")");
                var vals = sel.split(",");
                /*取得城市的父CODE*/
                var citys = object['citys'][vals[0]];
                $("#more_shi").empty();
                var citycode = '';
                for(var i=0;i<citys.length;i++)
                {
                    if(i==0)
                    {   citycode = citys[i]['addcode'];
                        $("#more_shi").append("<option selected='selected' value='"+citys[i]['addcode']+","+citys[i]['address']+"'>"+citys[i]['address']+"</option>");
                    }else{
                        $("#more_shi").append("<option  value='"+citys[i]['addcode']+","+citys[i]['address']+"'>"+citys[i]['address']+"</option>");
                    }
                }
                var districts = object['districts'][citycode];
                $("#more_qu").empty();
                for(var i=0;i<districts.length;i++)
                {
                    if(i==0)
                    {
                        $("#more_qu").append("<option selected='selected' value='"+districts[i]['addcode']+","+districts[i]['address']+"'>"+districts[i]['address']+"</option>");
                    }else{
                        $("#more_qu").append("<option  value='"+districts[i]['addcode']+","+districts[i]['address']+"'>"+districts[i]['address']+"</option>");
                    }

                }
                $("#more_shi").trigger("create");
                $("#more_qu").trigger("create");
                $("#more_shi").change(c_choice);
            }
        }
        function c_choice()
        {
        	var areadata = window.localStorage.getItem("areadata");
            var sel= $("#more_shi").find('option:selected').val();
            if(areadata!=null)
            {
                var object = eval("(" + areadata + ")");
                var vals = sel.split(",");
                var districts = object['districts'][vals[0]];
                $("#more_qu").empty();
                for(var i=0;i<districts.length;i++)
                {
                    if(i==0)
                    {
                        $("#more_qu").append("<option selected='selected' value='"+districts[i]['addcode']+","+districts[i]['address']+"'>"+districts[i]['address']+"</option>");
                    }else{
                        $("#more_qu").append("<option  value='"+districts[i]['addcode']+","+districts[i]['address']+"'>"+districts[i]['address']+"</option>");
                    }
                }
                $("#more_qu").trigger("create");
            }
        }

        /*修改收货地址*/
        function addeitd()
        {
        	closeMsg('');
            var more_shen=$("#more_shen").find("option:selected").text();
            var more_shi=$("#more_shi").find("option:selected").text();
            var more_qu=$("#more_qu").find("option:selected").text();
            var more_zip= $("#more_zip").val();
            var more_name= $("#more_name").val();
            var more_address= $("#more_address").val();
            var more_phone=  $("#more_phone").val();
            var more_mobile= $("#more_mobile").val();
				if(more_qu==""){
					more_qu=".";
					}
            var regu = /^[0-9a-zA-Z\_]+$/;
            var regzip = /^\d{6}$/;
            var regmobile = /^\d\d{7,15}$/;
            if(more_zip==''||more_name==''||more_address==''){
            	$("#hints").html('<p>亲，请填写完整的收货信息!</p>');
              	showMsg('hint');
              	$("input[msgstu='again']").attr("onclick","closeMsg('addr-table');");
            }else if(!regzip.test(more_zip)&&more_zip!=''){
                $("#hints").html('<p>邮编只能是6位数字!</p>');
              	showMsg('hint');
              	$("input[msgstu='again']").attr("onclick","closeMsg('addr-table');");
            }else if(more_address.length<4||more_address.length>60){
                $("#hints").html('<p>区县以下的街道地址最少要4个字，最多不能超过60个字！</p>');
              	showMsg('hint');
              	$("input[msgstu='again']").attr("onclick","closeMsg('addr-table');");
            }else if(more_phone==''&&more_mobile==''){
                $("#hints").html('<p>亲，电话和手机不能都为空!</p>');
              	showMsg('hint');
              	$("input[msgstu='again']").attr("onclick","closeMsg('addr-table');");
            }else if(regu.test(more_address)){
                $("#hints").html('<p>区县以下的街道地址不能全是字母，请重新填写！</p>');
              	showMsg('hint');
              	$("input[msgstu='again']").attr("onclick","closeMsg('addr-table');");
            }else if(!regmobile.test(more_mobile)&&more_mobile!=''){
                $("#hints").html('<p>手机号码必须由8到16位数字构成!</p>');
              	showMsg('hint');
              	$("input[msgstu='again']").attr("onclick","closeMsg('addr-table');");
            }else{
                QN.top.invoke({
                    "cmd": "taobao.trade.shippingaddress.update ",
                    "param":{
                        tid:gtid,
                        receiver_name:more_name,
                        receiver_phone:more_phone,
                        receiver_mobile:more_mobile,
                        receiver_state:more_shen,
                        receiver_city:more_shi,
                        receiver_district:more_qu,
                        receiver_address:more_address,
                        receiver_zip:more_zip
                    },
                    "method": "get",
                    "success" : function(rsp) {
                        if(typeof rsp === 'string'){
                            var rsp = JSON.parse(rsp);
                        }else{
                            var	rsp= rsp;
                        }
                        var rsperror=rsp.msg;
                        if(rsperror==undefined){
                        	$("#hints").html('<p>修改成功!</p>');
                          	showMsg('hint');
                            getdetail();
                        }else{
                            if(rsp.sub_msg){
                            	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
                              	showMsg('hint');
                            }else{
                            	geterrorinfo('taobao.trade.shippingaddress.update ',rsp);
                            }
                        }
                    },
                    error: function(msp){
                        if(typeof msp === 'string'){
                            var msp = JSON.parse(msp);
                        }else{
                            var	msp= msp;
                        }
                        if(msp.sub_code=='subuser.has-no-permission'){
                        	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                          	showMsg('hint');
                        }else{
                            if(msp.sub_msg){
                            	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                              	showMsg('hint');
                            }else{
                            	geterrorinfo('taobao.trade.shippingaddress.update ',msp);
                            }
                        }
                    }
                });
            }
        }
        /*发货*/
		var cdsend;
		/**
		 * 发货
		 */
		function sendplan(){
			closeMsg('');
			var num=0;
			var tids=new Array();
			var sub_tid='';
			$("input[name='batchcheckbox']:checked").each(
					function(){
						tids[num]=$(this).val();
						num++;
					} );
		    if(num==0){
		    	$("#hints").html('<p>请选择需要发货的订单！</p>');
		        showMsg('hint');
		        $("input[msgstu='again']").attr("onclick","closeMsg('senditem-table');");
		    }else{
		    		for(index in tids){
		    			sub_tid+=tids[index]+',';
		    		}
		    		if(cdsend==0){/*拆单发货*/
		    			cdtosendss(sub_tid)
		    		}else{
		        		if(num==cdsend){/*不拆弹发货*/
		        			zcsendplan();
		        		}else{/*拆单发货*/
		    			cdtosendss(sub_tid)
		        		}
		    		}
		    }
		}
		/**
		 * 正常发货
		 */
		function zcsendplan()
		{
		    var mode=$("#sendplan").find("option:selected").val();
		    var cycode=$("#comptyid").find("option:selected").val();
		    if(cycode=='OTHER'){
		    	cycode='other';
		    }
		    var outid= $("#postid").val();
		    var selleraddr=$("#selectaddrQ").val();
		    var sellerback=$("#selectbackaddr").val();
		    if(outid==''&&'notsend'!=mode){
		    	$("#hints").html('<p>运单号不能为空！</p>');
		        showMsg('hint');
		        $("input[msgstu='again']").attr("onclick","closeMsg('senditem-table');");
		        return;
		    }else{
		    var urlcode=cycode;
			if(cycode=='other'){
				cycode=$('#othercompany').val();
			}
			var parms={};
			if(selleraddr==null||sellerback==null){
				parms={
		               tid:gtid,
		               out_sid:outid,
		               company_code:cycode,
		          };
		    }else{
		   		parms={
		               tid:gtid,
		               out_sid:outid,
		               company_code:cycode,
		               sender_id:selleraddr,
		               cancel_id:sellerback
		          };
		    }
			
		    if('online'==mode){
		        QN.top.invoke({
		            "cmd": "taobao.logistics.online.send",
		            "param":parms,
		            "method": "post",
		            "success" : function(rsp) {
		                if(typeof rsp === 'string'){
		                    var rsp = JSON.parse(rsp);
		                }else{
		                    var	rsp= rsp;
		                }
		              $("#hints").html('<p>发货成功！</p>');
		             	showMsg('hint');
						$('#dfh_list').empty();
						$('#yfh_list').empty();
						$('#all_list').empty();
		                getdetail();
						if(lastmodes==mode&&lasttrade==urlcode){
						}else{
				
				               		$.ajax({
					             		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/tosend',
					             		    type: 'POST',
					             		    dataType:'html',
					             		    data:{nick:user_nick,mode:mode,offtrade:urlcode},
					             		    timeout:10000,
				         		        	success: function(data, textStatus){
				         		        		var datas = window.localStorage.getItem("compty"+user_nick);
				                    		        if(datas.length>3){
				                    		        	datas=JSON.parse(datas);
				                    		        	for(index in datas){
				                        		        	if(datas[index].mode=='online'){
				                        		        		datas[index].last_way=clearBr(data);
				                        		        		break;
				                        		        	}
				                    		        	}
				                    		        	datas=JSON.stringify(datas);
				                   		        	 window.localStorage.setItem("compty"+user_nick,datas);
				                    		        }
				         	        	},
				         	 	       error: function(){
				         	        	}
				   	      	    });
						}
		            },
		            error: function(msp){
		                if(typeof msp === 'string'){
		                    var msp = JSON.parse(msp);
		                }else{
		                    var	msp= msp;
		                }
		                if(msp.sub_code=='subuser.has-no-permission'){
		                	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
		                    showMsg('hint');
		                }else if(msp.sub_code=='isv.logistics-online-service-error:B02'){
		                	$("#hints").html('<p>您的帐号没有发货的权限!</p>');
		             		 showMsg('hint');
		             		 
		          		}else if(msp.sub_code=='isv.logistics-online-service-error:B04'){
		  	          			$("#hints").html('<p>订单状态不对。您已使用“在线下单”方式对此订单进行发货操作，请前往卖家中心核实：)</p>');
		  	  	          		 showMsg('hint');
		          		}else if(msp.sub_code=='isv.logistics-online-service-error:B101'){
		  	          			$("#hints").html('<p>您还没设置默认的退发货地址</p>');
		  	  	          		 showMsg('hint');
		          		}else if(msp.sub_code=='isv.logistics-online-service-error:B79'){
		  	          			$("#hints").html('<p>该物流公司揽收或派送范围不支持</p>');
		  	  	          		 showMsg('hint');
		          		}else if(msp.sub_code=='isv.logistics-online-service-error:B55'){
		  	          			$("#hints").html('<p>该交易状态不正确，不能发货</p>');
		  	  	          		 showMsg('hint');
		          		}else if(msp.msg=='Invalid arguments:sender_id'){
		                	$("#hints").html('<p>发货地址异常，请检查你的发货地址！</p>');
		                    showMsg('hint');
		                }else{
		                	geterrorinfo("taobao.logistics.online.send",msp);
		                }

		            }
		        });
		    }else if('offline'==mode){
		        QN.top.invoke({
		            "cmd": "taobao.logistics.offline.send",
		            "param":parms,
		            "method": "post",
		            "success" : function(rsp) {
		                if(typeof rsp === 'string'){
		                    var rsp = JSON.parse(rsp);
		                }else{
		                    var	rsp= rsp;
		                }
		              $("#hints").html('<p>发货成功！</p>');
		             	showMsg('hint');
						$('#dfh_list').empty();
						$('#yfh_list').empty();
						$('#all_list').empty();
		                getdetail();
						if(lastmodes==mode&&lasttrade==urlcode){
						}else{
				
				               		$.ajax({
					             		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/tosend',
					             		    type: 'POST',
					             		    dataType:'html',
					             		    data:{nick:user_nick,mode:mode,offtrade:urlcode},
					             		    timeout:10000,
				         		        	success: function(data, textStatus){
				         		        		var datas = window.localStorage.getItem("compty"+user_nick);
				                    		        if(datas.length>3){
				                    		        	datas=JSON.parse(datas);
				                    		        	for(index in datas){
				                        		        	if(datas[index].mode=='online'){
				                        		        		datas[index].last_way=clearBr(data);
				                        		        		break;
				                        		        	}
				                    		        	}
				                    		        	datas=JSON.stringify(datas);
				                   		        	 window.localStorage.setItem("compty"+user_nick,datas);
				                    		        }
				         	        	},
				         	 	       error: function(){
				         	        	}
				   	      	    });
						}
		            },
		            error: function(msp){
		                if(typeof msp === 'string'){
		                    var msp = JSON.parse(msp);
		                }else{
		                    var	msp= msp;
		                }
		                if(msp.sub_code=='subuser.has-no-permission'){
		                	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
		  	                showMsg('hint');
		                }else if(msp.sub_code=='isv.logistics-offline-service-error:B02'){
		  					$("#hints").html('<p>您的帐号没有发货的权限!</p>');
		  					 showMsg('hint');
		      			}else if(msp.sub_code=='isv.logistics-offline-service-error:B04'){
		      				$("#hints").html('<p>订单状态不对。您已使用“在线下单”方式对此订单进行发货操作，请前往卖家中心核实：)</p>');
		      				 showMsg('hint');
		      			}else if(msp.sub_code=='isv.logistics-offline-service-error:B101'){
		      				$("#hints").html('<p>您还没设置默认的退发货地址</p>');
		      				 showMsg('hint');
		      			}else if(msp.sub_code=='isv.logistics-offline-service-error:B57'){
		      				$("#hints").html('<p>该物流公司不支持自己联系</p>');
		      				 showMsg('hint');
		      			}else if(msp.sub_code=='isv.logistics-offline-service-error:B55'){
		      				$("#hints").html('<p>该交易状态不正确，不能发货</p>');
		      				 showMsg('hint');
		      			}else{
		      				geterrorinfo("taobao.logistics.offline.send",msp);
		                }
		            }
		        });
		    }else if('notsend'==mode){
		        QN.top.invoke({
		            "cmd": "taobao.logistics.dummy.send",
		            "param":{
		                tid:gtid
		            },
		            "method": "post",
		            "success" : function(rsp) {
		                if(typeof rsp === 'string'){
		                    var rsp = JSON.parse(rsp);
		                }else{
		                    var	rsp= rsp;
		                }
		              $("#hints").html('<p>发货成功！</p>');
		             	showMsg('hint');
						$('#dfh_list').empty();
						$('#yfh_list').empty();
						$('#all_list').empty();
		                getdetail();
						if(lastmodes==mode&&lasttrade==urlcode){
						}else{
				
				               		$.ajax({
					             		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/tosend',
					             		    type: 'POST',
					             		    dataType:'html',
					             		    data:{nick:user_nick,mode:mode,offtrade:urlcode},
					             		    timeout:10000,
				         		        	success: function(data, textStatus){
				         		        		var datas = window.localStorage.getItem("compty"+user_nick);
				                    		        if(datas.length>3){
				                    		        	datas=JSON.parse(datas);
				                    		        	for(index in datas){
				                        		        	if(datas[index].mode=='online'){
				                        		        		datas[index].last_way=clearBr(data);
				                        		        		break;
				                        		        	}
				                    		        	}
				                    		        	datas=JSON.stringify(datas);
				                   		        	 window.localStorage.setItem("compty"+user_nick,datas);
				                    		        }
				         	        	},
				         	 	       error: function(){

				         	        	}
				   	      	    });
						}
		            },
		            error: function(msp){
		                if(typeof msp === 'string'){
		                    var msp = JSON.parse(msp);
		                }else{
		                    var	msp= msp;
		                }
		                if(msp.sub_code=='subuser.has-no-permission'){
		                	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
		  	                showMsg('hint');
		                }else{
		                    if(msp.sub_msg){
		                    	$("#hints").html('<p>无需物流错误:'+msp.sub_msg+'</p>');
		      	                showMsg('hint');
		        	            $("input[msgstu='again']").attr("onclick","closeMsg('senditem-table');");
		                    }else{
		                    	geterrorinfo("taobao.logistics.dummy.send",msp);
		                    }
		                }
		            }
		        });
		    }
		    }
		}
		/**
		 * 拆单发货
		 */
		function cdtosendss(sub_tid)
		{
		   var mode=$("#sendplan").find("option:selected").val();
		   var cycode=$("#comptyid").find("option:selected").val();
		   var outid= $("#postid").val();
		   var selleraddr=$("#selectaddrQ").val();
		   var sellerback=$("#selectbackaddr").val();
		   
		   if(cycode=='OTHER'){
		   	cycode='other';
		   }
		   if(outid==''&&'notsend'!=mode){
		   	$("#hints").html('<p>运单号不能为空！</p>');
		       showMsg('hint');
		       $("input[msgstu='again']").attr("onclick","closeMsg('senditem-table');");
		   }else{
		   var urlcode=cycode;
			if(cycode=='other'){
				cycode=$('#othercompany').val();
			}
			
			var parms={};
		   if(selleraddr==null||sellerback==null){
				parms={
		               tid:gtid,
		               out_sid:outid,
		               is_split:'1',
		               sub_tid:sub_tid,
		               company_code:cycode,
		          };
		   }else{
		   		parms={
		               tid:gtid,
		               out_sid:outid,
		               is_split:'1',
		               sub_tid:sub_tid,
		               company_code:cycode,
		               sender_id:selleraddr,
		               cancel_id:sellerback
		          };
		   }

		   if('online'==mode){
		       QN.top.invoke({
		           "cmd": "taobao.logistics.online.send",
		           "param":parms,
		           "method": "get",
		           "success" : function(rsp) {
		               if(typeof rsp === 'string'){

		                   var    rsp = JSON.parse(rsp);
		               }else{
		                   var	rsp= rsp;
		               }
		                $("#hints").html('<p>发货成功！</p>');
		             	showMsg('hint');
						$('#dfh_list').empty();
						$('#yfh_list').empty();
						$('#all_list').empty();
		                getdetail();
						if(lastmodes==mode&&lasttrade==urlcode){
						}else{
				
				               		$.ajax({
					             		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/tosend',
					             		    type: 'POST',
					             		    dataType:'html',
					             		    data:{nick:user_nick,mode:mode,offtrade:urlcode},
					             		    timeout:10000,
				         		        	success: function(data, textStatus){
				         		        		var datas = window.localStorage.getItem("compty"+user_nick);
				                    		        if(datas.length>3){
				                    		        	datas=JSON.parse(datas);
				                    		        	for(index in datas){
				                        		        	if(datas[index].mode=='online'){
				                        		        		datas[index].last_way=clearBr(data);
				                        		        		break;
				                        		        	}
				                    		        	}
				                    		        	datas=JSON.stringify(datas);
				                   		        	 window.localStorage.setItem("compty"+user_nick,datas);
				                    		        }
				         	        	},
				         	 	       error: function(){
				         	        	}
				   	      	    });
						}
		           },
		           error: function(msp){
		               if(typeof msp === 'string'){
		                   var msp = JSON.parse(msp);
		               }else{
		                   var	msp= msp;
		               }
		               if(msp.sub_code=='subuser.has-no-permission'){
		               	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
		                   showMsg('hint');
		               }else if(msp.sub_code=='isv.logistics-online-service-error:B02'){
		               	$("#hints").html('<p>您的帐号没有发货的权限!</p>');
		            		 showMsg('hint');
		            		 
		         		}else if(msp.sub_code=='isv.logistics-online-service-error:B04'){
		 	          			$("#hints").html('<p>订单状态不对。您已使用“在线下单”方式对此订单进行发货操作，请前往卖家中心核实：)</p>');
		 	  	          		 showMsg('hint');
		         		}else if(msp.sub_code=='isv.logistics-online-service-error:B101'){
		 	          			$("#hints").html('<p>您还没设置默认的退发货地址</p>');
		 	  	          		 showMsg('hint');
		         		}else if(msp.sub_code=='isv.logistics-online-service-error:B79'){
		 	          			$("#hints").html('<p>该物流公司揽收或派送范围不支持</p>');
		 	  	          		 showMsg('hint');
		         		}else if(msp.sub_code=='isv.logistics-online-service-error:B55'){
		 	          			$("#hints").html('<p>该交易状态不正确，不能发货</p>');
		 	  	          		 showMsg('hint');
		         		}else if(msp.msg=='Invalid arguments:sender_id'){
		               	$("#hints").html('<p>发货地址异常，请检查你的发货地址！</p>');
		                   showMsg('hint');
		               }else{
		               	geterrorinfo("taobao.logistics.online.send",msp);
		               }

		           }
		       });
		   }else if('offline'==mode){
		       QN.top.invoke({
		           "cmd": "taobao.logistics.offline.send",
		           "param":parms,
		           "method": "get",
		           "success" : function(rsp) {
		               if(typeof rsp === 'string'){
		                   var rsp = JSON.parse(rsp);
		               }else{
		                   var	rsp= rsp;
		               }
		               $("#hints").html('<p>发货成功！</p>');
		             	showMsg('hint');
						$('#dfh_list').empty();
						$('#yfh_list').empty();
						$('#all_list').empty();
		                getdetail();
						if(lastmodes==mode&&lasttrade==urlcode){
						}else{
				
				               		$.ajax({
					             		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/tosend',
					             		    type: 'POST',
					             		    dataType:'html',
					             		    data:{nick:user_nick,mode:mode,offtrade:urlcode},
					             		    timeout:10000,
				         		        	success: function(data, textStatus){
				         		        		var datas = window.localStorage.getItem("compty"+user_nick);
				                    		        if(datas.length>3){
				                    		        	datas=JSON.parse(datas);
				                    		        	for(index in datas){
				                        		        	if(datas[index].mode=='online'){
				                        		        		datas[index].last_way=clearBr(data);
				                        		        		break;
				                        		        	}
				                    		        	}
				                    		        	datas=JSON.stringify(datas);
				                   		        	 window.localStorage.setItem("compty"+user_nick,datas);
				                    		        }
				         	        	},
				         	 	       error: function(){
				         	        	}
				   	      	    });
						}
		           },
		           error: function(msp){
		               if(typeof msp === 'string'){
		                   var msp = JSON.parse(msp);
		               }else{
		                   var	msp= msp;
		               }
		               if(msp.sub_code=='subuser.has-no-permission'){
		               	 $("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
		 	                showMsg('hint'); 
		               }else if(msp.sub_code=='isv.logistics-offline-service-error:B02'){
		 					$("#hints").html('<p>您的帐号没有发货的权限!</p>');
		 					 showMsg('hint');
		     			}else if(msp.sub_code=='isv.logistics-offline-service-error:B04'){
		     				$("#hints").html('<p>订单状态不对。您已使用“在线下单”方式对此订单进行发货操作，请前往卖家中心核实：)</p>');
		     				 showMsg('hint');
		     			}else if(msp.sub_code=='isv.logistics-offline-service-error:B101'){
		     				$("#hints").html('<p>您还没设置默认的退发货地址</p>');
		     				 showMsg('hint');
		     			}else if(msp.sub_code=='isv.logistics-offline-service-error:B57'){
		     				$("#hints").html('<p>该物流公司不支持自己联系</p>');
		     				 showMsg('hint');
		     			}else if(msp.sub_code=='isv.logistics-offline-service-error:B55'){
		     				$("#hints").html('<p>该交易状态不正确，不能发货</p>');
		     				 showMsg('hint');
		     			}else{
		     				geterrorinfo("taobao.logistics.offline.send",msp);
		               }

		           }
		       });
		   }else if('notsend'==mode){/*无需物流7*/
		       QN.top.invoke({
		           "cmd": "taobao.logistics.dummy.send",
		           "param":{
		               tid:gtid
		           },
		           "method": "get",
		           "success" : function(rsp) {
		               if(typeof rsp === 'string'){
		                   var rsp = JSON.parse(rsp);
		               }else{
		                   var	rsp= rsp;
		               }
		               $("#hints").html('<p>发货成功！</p>');
		             	showMsg('hint');
						$('#dfh_list').empty();
						$('#yfh_list').empty();
						$('#all_list').empty();
		                getdetail();
						if(lastmodes==mode&&lasttrade==urlcode){
						}else{
				
				               		$.ajax({
					             		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/tosend',
					             		    type: 'POST',
					             		    dataType:'html',
					             		    data:{nick:user_nick,mode:mode,offtrade:urlcode},
					             		    timeout:10000,
				         		        	success: function(data, textStatus){
				         		        		var datas = window.localStorage.getItem("compty"+user_nick);
				                    		        if(datas.length>3){
				                    		        	datas=JSON.parse(datas);
				                    		        	for(index in datas){
				                        		        	if(datas[index].mode=='online'){
				                        		        		datas[index].last_way=clearBr(data);
				                        		        		break;
				                        		        	}
				                    		        	}
				                    		        	datas=JSON.stringify(datas);
				                   		        	 window.localStorage.setItem("compty"+user_nick,datas);
				                    		        }
				         	        	},
				         	 	       error: function(){
				         	        	}
				   	      	    });
						}
		           },
		           error: function(msp){
		               if(typeof msp === 'string'){
		                   var msp = JSON.parse(msp);
		               }else{
		                   var	msp= msp;
		               }
		               if(msp.sub_code=='subuser.has-no-permission'){
		              $("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
		 	                showMsg('hint'); 
		               }else{
		                   if(msp.sub_msg){
		                   	$("#hints").html('<p>无需物流错误：'+msp.sub_msg+'！</p>');
		     	                showMsg('hint');
		                   }else{
		                   	geterrorinfo("taobao.logistics.dummy.send",msp);
		                   }
		               }

		           }
		       });
		   }
		   }
		}
        /**
         * 加载物流公司
         * 1.获取数据
         * @author Duanhq
         */
        function getcompty(changeoff){
        		var comptydata = window.localStorage.getItem("compty"+user_nick);
        		if(comptydata==null||comptydata=="null"|| typeof(comptydata)=="undefined"||comptydata.length<4)
        		{
        			$.ajax({
                 		url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/getsend',
                 		type: 'POST',
                 		dataType:'html',
                 		data:{nick:user_nick},
                 		timeout:10000,
        				error: function(){
        					loaddatass(comptydata,changeoff);
        				},
        				success: function(data){
        					if(data.length>3)
                             {
                                 window.localStorage.setItem("compty"+user_nick,data);
                             }
        					loaddatass(data,changeoff);
        				}
        			});
        		}else{
        			loaddatass(comptydata,changeoff);
        		}
        }
        /**
         * 加载物流公司
         * 2.业务处理
         * @author Duanhq
         */
        var lastmodes="";/*上次发货的记录*/
        var lasttrade="";/*上一次发货的公司*/
        function loaddatass(data,changeoff){
        	$("#wuliush1").show();
        	$("#wuliush2").show();
        	$("#off_other").empty();
        	if(data==null|| typeof(data)=="undefined"||data==''||data.length<4){
        	}else{
            	data=JSON.parse(data);
        	}
        	var name='';
            var code='';
            var datas={};
            datas.lastmode=new Array();
        	datas.lastmode[0]='offline';
        	datas.lastmode[1]='';
            datas.onname='';
            datas.oncode='';
            datas.offname='';
            datas.offcode='';
            for(index in data){
                order=data[index];
                /*在线下单，卖家是否在数据库中存储了默认快递公司*/
                	if(order.mode=='online'){
                		if(order.last_way!=null){
                			datas.lastmode=order.last_way.split(",");
                			if(datas.lastmode[1]==null){
                				datas.lastmode[1]='';
                			}
                		}
                		if(order.name!=null){
                			datas.onname=order.name.split(",");/*快递公司名字*/
                			datas.oncode=order.code.split(",");/*快递公司编码*/
                		}
                	}else if(order.mode=='offline'){
                		if(order.name!=null){
                			datas.offname=order.name.split(",");/*快递公司名字*/
                			datas.offcode=order.code.split(",");/*快递公司编码*/
                		}
                	}
            }
        	if(changeoff!=null){
        		if(changeoff=='offline'){
        	    	datas.mode='offline';
        	    	if(datas.offname!=''&&datas.offname!=null){
        	    	    name=datas.offname;
        	    	}else{
        	    	    name='';
        	    	}
        	    	if(datas.offcode!=''&&datas.offcode!=null){
        	    	    code=datas.offcode;
        	    	}else{
        	    	    code='';
        	    	}
        	    	$("#sendplan option[value='offline']").attr("selected","selected");
        	    }else if(changeoff=='online'){
                    datas.mode='online';
                    if(datas.onname!=''&&datas.onname!=null){
                        name=datas.onname;
                    }else{
                    	name='';
                    }
                    if(datas.oncode!=''&&datas.oncode!=null){
                        code=datas.oncode;
                    }else{
                    	code='';
                    }
        	    	$("#sendplan option[value='online']").attr("selected","selected");
        	    }else if(changeoff=='notsend'){
        			name='no';
        			name='no';
        			$("#sendplan option[value='notsend']").attr("selected","selected");
        	    }
        	}else{
        		lastmodes=datas.lastmode[0];
            	lasttrade=datas.lastmode[1];
                if(datas.lastmode[0]=='offline'){
                    datas.mode='offline';
                    if(datas.offname!=''&&datas.offname!=null){
                        name=datas.offname;
                    }else{
                    	name='';
                    }
                    if(datas.offcode!=''&&datas.offcode!=null){
                        code=datas.offcode;
                    }else{
                    	code='';
                    }
        	    	$("#sendplan option[value='offline']").attr("selected","selected");
        		}else if(datas.lastmode[0]=='online'){
                    datas.mode='online';
                    if(datas.onname!=''&&datas.onname!=null){
                        name=datas.onname;
                    }else{
                    	name='';
                    }
                    if(datas.oncode!=''&&datas.oncode!=null){
                        code=datas.oncode;
                    }else{
                    	code='';
                    }
        			$("#sendplan option[value='online']").attr("selected","selected");
        		}else if(datas.lastmode[0]=='notsend'){
        			name='no';
        			name='no';
        			$("#sendplan option[value='notsend']").attr("selected","selected");
        		}else{
                    datas.mode='offline';
                    if(datas.offname!=''&&datas.offname!=null){
                        name=datas.offname;
                    }else{
                    	name='';
                    }
                    if(datas.offcode!=''&&datas.offcode!=null){
                        code=datas.offcode;
                    }else{
                    	code='';
                    }
        	    	$("#sendplan option[value='offline']").attr("selected","selected");
        		}
        	}
        	if(name!=''&&name!='no'){
        		$("#comptyid").empty();
        		for(index in name){
        			datas.name=name[index];
        			datas.code=code[index];
        			if(datas.lastmode[1]!=''&&datas.lastmode[1]!=null){
        				if(datas.code==datas.lastmode[1]){
        					$("#comptyid").append('<option value="'+datas.code+'" selected=selected>'+datas.name+'</option>');
                        }else{
        					$("#comptyid").append('<option value="'+datas.code+'">'+datas.name+'</option>');
        				}
        			}else{
                          	$("#comptyid").append('<option value="'+datas.code+'">'+datas.name+'</option>');
                    }
                }
        		if(datas.mode=='offline'){
        			$("#comptyid").append("<option  value='others'>其它物流公司</option>");
        			
        		}
        		if(datas.lastmode[1]=='other'){
        			$("#comptyid option[value='other']").attr("selected","selected");		
        		}
        		c_offline();
        	}else if(name=='no'){/*上一次选择了无需物流*/
        	        $("#wuliush1").hide();
        	        $("#wuliush2").hide();
              	    $("#off_other").empty();
        	}else{/*默认快递公司为空,则通过条用淘宝接口列出所有快递公司供选择*/
        		QN.top.invoke({
        			"cmd": "taobao.logistics.companies.get",
        			"param": {fields:'code,name',is_recommended:true,order_mode:datas.mode},
        			"method": "get",
        			"success": function (rsp){
        				if(typeof  rsp=== 'string'){
        					rsp = JSON.parse(rsp);
        				}
        				try{
        					$('#comptyid').empty();
        					for(index in rsp.logistics_companies_get_response.logistics_companies.logistics_company){
        						var order=rsp.logistics_companies_get_response.logistics_companies.logistics_company[index];
        						var datas={};
        						datas.name=order.name;
                      	    	datas.code=order.code;
           		                if(lasttrade!=''&&lasttrade!=null){
           		                    if(datas.code==lasttrade){
           		                       	$("#comptyid").append('<option value="'+datas.code+'" selected=selected>'+datas.name+'</option>');
           		                    }else{
           	   		                    $("#comptyid").append('<option value="'+datas.code+'">'+datas.name+'</option>');
              		                }
           		                }else{
           		                    $("#comptyid").append('<option value="'+datas.code+'">'+datas.name+'</option>');
           		                }
                  	    	}
                  	    	if($("#sendplan").find("option:selected").val()=='offline'){
                      		    $("#comptyid").append("<option  value='other'>其它</option>");
                            }
                            c_offline();

        				}catch(e){
        					$("#hints").html('<p>'+e+'</p>');
        					showMsg('hint');
        				}
                	}
        		});
        	}
        }
        /**
         * 物流方式更改后事件
         */
        function a_offline(){
        	var sel=$('#sendplan').find("option:selected").val();
            $("#wuliush1").show();
            $("#wuliush2").show();
            getcompty(sel);
        	if(sel=='notsend'||sel=='online'){
        		$("#off_other").empty();
        	}else{
        		c_offline();
        	}
        }
        /**
         * 物流公司更改后事件
         */
        function c_offline()
        {
        	$("#off_other").empty();
        	var sel = $("#comptyid").find("option:selected").val();
        	if(sel=='other'||sel=='OTHER')
        	{
        		
        		$("#off_other").append("<p><input type='text' name='othercompany' id='othercompany' placeholder='请输入物流公司'></input></p>");
        	}else if(sel=='others'){
        		d_offline();
        	}
        }
        /**
         * 物流公司更改后事件:选中其他物流公司
         */
        function d_offline(){
        	QN.top.invoke({
        		"cmd": "taobao.logistics.companies.get",
        		"param": {fields:'code,name',is_recommended:true,order_mode:'offline'},
        		"method": "get",
        		"success": function (rsp){
                    if(typeof  rsp=== 'string'){
                    	rsp = JSON.parse(rsp);
                    }
                    if(rsp.code!=null){
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>在线：'+rsp.sub_msg+'</p>');
          	                showMsg('hint');
                        }else{
                        	geterrorinfo("taobao.logistics.companies.get",rsp);
                        }
                    }else{
        	    			$('#comptyid').empty();
        	    			 for(index in rsp.logistics_companies_get_response.logistics_companies.logistics_company){
            	    			 var order=rsp.logistics_companies_get_response.logistics_companies.logistics_company[index];
        						var datas={};
            	    			 datas.name=order.name;
            	    			 datas.code=order.code;
                                if(lasttrade!=''&&lasttrade!=null){
                               		if(datas.code==lasttrade){
                               			$("#comptyid").append('<option value="'+datas.code+'" selected=selected>'+datas.name+'</option>');
                                	}else{
                                      	$("#comptyid").append('<option value="'+datas.code+'">'+datas.name+'</option>');
                                    }
                                }else{
                                	$("#comptyid").append('<option value="'+datas.code+'">'+datas.name+'</option>');
                                }
        	    			 }
        	    				 $("#comptyid").append("<option  value='POST'>中国邮政平邮</option>");
        	    		    	 if($("#sendplan").find("option:selected").val()=='offline'){
        	    		    	 	if(lasttrade=='other'){
        	    		    	 		$("#comptyid").append("<option  value='other' selected=selected>其它</option>");
        	    		    	 		c_offline();
        	    		    	 	}else{
        	    		    		 	$("#comptyid").append("<option  value='other'>其它</option>");
        	    		    		 }
            		    		 }
                    }
        	    		},
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	 $("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
        	                showMsg('hint'); 
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>在线错误：'+msp.sub_msg+'</p>');
          	                showMsg('hint');
                        }else{
                        	geterrorinfo("taobao.logistics.companies.get",msp);
                        }
                    }
                }
        	});
        }
    /*货到付款*/
    function codsendplan()
    {
    	closeMsg('');
        var cycode=$("#codcomptyid").find("option:selected").val();
        var codoutid= $("#codpostid").val();
        var selleraddr=$("#selectaddrW").val();
        var sellerback=$("#selectbackaddrQ").val();    
        codoutid=clearBr(codoutid);
        if(codoutid!=''){
            QN.top.invoke({
                "cmd": "taobao.logistics.online.send",
                "param":{
                    tid:gtid,
                    out_sid:codoutid,
                    company_code:cycode,
                    sender_id:selleraddr,
                    cancel_id:sellerback
                },
                "method": "get",
                "success" : function(rsp) {
                    if(typeof rsp === 'string'){
                        var rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    var rsperror=rsp.msg;
                    if(rsperror==undefined){
                    	$("#hints").html('<p>修改成功！</p>');
    	              	showMsg('hint');
                        getdetail();
                    }else{
                        if(rsp.sub_msg){
                        	$("#hints").html('<p>'+rsp.sub_msg+'</p>');
        	              	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.logistics.online.send',rsp);
                        }
                    }
                },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
    	              	showMsg('hint'); 
                    }else if(msp.sub_code=='isv.logistics-offline-service-error:B02'){
                    	$("#hints").html('<p>您的帐号没有发货的权限!</p>');
                 		 showMsg('hint');
	          			}else if(msg.sub_code=='isv.logistics-offline-service-error:B04'){
	  	          			$("#hints").html('<p>订单状态不对</p>');
	  	  	          		 showMsg('hint');
	          			}else if(msp.sub_code=='isv.logistics-offline-service-error:B101'){
	  	          			$("#hints").html('<p>您还没设置默认的退发货地址</p>');
	  	  	          		 showMsg('hint');
	          			}else if(msp.sub_code=='isv.logistics-online-service-error:B79'){
	  	          			$("#hints").html('<p>该物流公司揽收或派送范围不支持</p>');
	  	  	          		 showMsg('hint');
	          			}else if(msp.sub_code=='isv.logistics-offline-service-error:B55'){
	  	          			$("#hints").html('<p>该交易状态不正确，不能发货</p>');
	  	  	          		 showMsg('hint');
	          			}else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
        	              	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.logistics.online.send',msp);
                        }
                    }

                }
            });
        }else{
        	$("#hints").html('<p>运单号不能为空！</p>');
          	showMsg('hint');
          	$("input[msgstu='again']").attr("onclick","closeMsg('sendcoditem-table');");
        }
    }
        /*******************日期时间转换unix时间戳****************/
        function datetime_to_unix(datetime){
            var tmp_datetime = datetime.replace(/:/g,'-');
            tmp_datetime = tmp_datetime.replace(/ /g,'-');
            var arr = tmp_datetime.split("-");
            var now = new Date(Date.UTC(arr[0],arr[1]-1,arr[2],arr[3]-8,arr[4],arr[5]));
            return parseInt(now.getTime()/1000);
        }
        /*******************获取时间,0为今天,-1为一天前****************/
        function GetDateStr(AddDayCount){
            var dd = new Date();
            dd.setDate(dd.getDate()+AddDayCount);/*获取AddDayCount天后的日期*/
            var y = dd.getFullYear();
            var m = dd.getMonth()+1;/*获取当前月份的日期*/
            var d = dd.getDate();
            return dd.format();
        }
        /**************************系统*******************/
        /*时间格式化*/
        Date.prototype.format = function(format){
            if(!format){
                format = "yyyy-MM-dd hh:mm:ss";
            }
            var o = {
                "M+": this.getMonth() + 1, /* month*/
                "d+": this.getDate(), /* day*/
                "h+": this.getHours(), /* hour*/
                "m+": this.getMinutes(), /* minute*/
                "s+": this.getSeconds(), /* second*/
                "q+": Math.floor((this.getMonth() + 3) / 3), /* quarter*/
                "S": this.getMilliseconds()

            };
            if (/(y+)/.test(format)) {
                format = format.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
            }
            for (var k in o) {
                if (new RegExp("(" + k + ")").test(format)) {
                    format = format.replace(RegExp.$1, RegExp.$1.length == 1 ? o[k] : ("00" + o[k]).substr(("" +o[k]).length));
                }
            }
            return format;
        };
    /*添加评价快捷短语*/
    function Pconchoice(valac){
        var selec= $("#conpj"+valac).find('option:selected').val();
        $("#trate"+valac).val(selec);
    }
    function memochoice(){
        var selec= $("#memone").find('option:selected').val();
        $("#beiwtext").val(selec);
    }
    /*获取卖家备注留言快捷短语*/
    function getmymemo(){
    	$.ajax({
		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/getFast',
		    type: 'POST',
		    dataType:'html',
		    data:{nick:user_nick,types:'fast_beiw'},
		    timeout:10000,
            success: function(dataP){ /*获取成功*/
                var dataPs=dataP;
                $(".conmemo").empty();
                $(".conmemo").append('<option  value="">请选择常用短语</option>');
                var valP=dataPs.split('\\n');
                console.log(valP);
                if(valP[0].indexOf('\n') > 0 ) valP=dataPs.split('\n');
                console.log(valP);
                console.log(valP.length);
                if(valP!=null&&valP.length>0){
                    for(index in valP){
                        $(".conmemo").append('<option  value="'+valP[index]+'">'+valP[index]+'</option>');
                    }
                }
            }
        });
    }
    function getmypjcon(){
    	$.ajax({
		    url: '<?php echo APP_WEB_INDEX_ROOT;?>/iytrade/getPing',
		    type: 'POST',
		    dataType:'html',
		    data:{nick:user_nick},
		    timeout:10000,
            success: function(dataP){ /*获取成功*/
                var dataPs=dataP;
                $(".conpj").empty();
                var valP=dataPs.split('\\n');
                if(valP[0].indexOf('\n') > 0 ) valP=dataPs.split('\n');
                if(valP!=null&&valP.length>1){
                    for(index in valP){
                        $(".conpj").append('<option  value="'+valP[index]+'">'+valP[index]+'</option>');
                    }
                }
                $("[name='initpcon']").html(valP[0]);
            }
        });
    }
    function sendwuliuw(nick,con){
        var text=$("p.dintro:last").text();
        if(text==''){
            wangwangPC(nick,con);
        }else{
            wangwangPC(nick,con+'\n'+text);
        }
     }
    /*
    免登跳支付宝
     */
    function goalipay(nick,alipayemail){
        var alipayev=encodeURI(alipayemail);
        var urlval="https://lab.alipay.com/life/payment/fill.htm?taobaonick="+nick+"&optEmail="+alipayev;
        window.open(urlval);
    }

    /*
     编辑订单属性
     */
    function editsku(oid,num_iid,pic_path,title,price,num,properties){
        QN.top.invoke({
            "cmd": "taobao.item.get",
            "param":{
                fields:'sku.properties_name,sku.properties,sku.quantity,sku.price,property_alias',
                num_iid:num_iid
            },
            "method": "get",
            "success" : function(rsp) {
                if(typeof rsp === 'string'){
                    var rsp = JSON.parse(rsp);
                }else{
                    var	rsp= rsp;
                }
                var datas={};
                datas.pic_path=pic_path;
                datas.title=title;
                datas.price=price;
                datas.num=num;
                datas.num_iid=num_iid;
                datas.properties=properties;
                var propertiename='';
                var provals='';
                var proname='';
                var pronametext='';
                var skus=rsp.item_get_response.item.skus.sku;
                var  property_alias=rsp.item_get_response.item.property_alias;
                property_alias=property_alias.split(';');
                var proalias ={};
                for(var i in property_alias){
                  var alias= property_alias[i].split(':');
                    var id=''+alias[0]+alias[1];
                    proalias[id]=alias[2];
                }
                for(var index in skus){
                     propertiename=skus[index].properties_name;
                     provals=propertiename.split(';');
                     for(var j in provals){
                         proname=provals[j].split(':');
                         if(proname!=''){
                             if(j!=0){
                                 if(proalias[proname[0]+proname[1]]){
                                    pronametext+=';'+proname[2]+':'+proalias[''+proname[0]+proname[1]];
                                 }else{
                                    pronametext+=';'+proname[2]+':'+proname[3];
                                 }
                             }else{
                                if(proalias[''+proname[0]+proname[1]]){
                                    pronametext=proname[2]+':'+proalias[''+proname[0]+proname[1]];
                                }else{
                                    pronametext=proname[2]+':'+proname[3];
                                }
                             }
                         }
                     }
                     if(properties==pronametext){
                      	skus[index].isprosku="selected=\"selected\"";
                      }
                    skus[index].properties_name=pronametext;
                }
                datas.skus=skus;
                var source = $("#skudata_template").html();
                var template = Handlebars.compile(source);
                var htmlstr = template(datas);
                $("#skubody").html(htmlstr);
                $("#savesku").attr("onclick","savesku('"+oid+"')");
                radclick();
                showMsg('skuedit-table');
            },
            error: function(msp){
                if(typeof msp === 'string'){
                    var msp = JSON.parse(msp);
                }else{
                    var	msp= msp;
                }
                if(msp.sub_code=='subuser.has-no-permission'){
                	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                  	showMsg('hint');
                }else{
                    if(msp.sub_msg){
                    	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                      	showMsg('hint');
                    }else{
                    	geterrorinfo('taobao.item.get',msp);
                    }
                }

            }
        });
    }
    function radclick(){
        var provl= $("#selectsku").find('option:selected').val();
        provl=provl.split(",");
        $("#skuprice").html(provl[1]);
        $("#skunum").html(provl[2]);
    }
    function savesku(oid){
    	closeMsg('');
        var provl= $("#selectsku").find('option:selected').val();
        provl=provl.split(",");
        var properties=provl[0];
        if(properties==''||oid==''){
        	$("#hints").html('<p>操作失败，请重试！</p>');
          	showMsg('hint');
        }else{
            QN.top.invoke({
                "cmd": "taobao.trade.ordersku.update",
                "param":{
                    oid:oid,
                    sku_props:properties
                },
                "method": "get",
                "success" : function(rsp) {
                    if(typeof rsp === 'string'){
                        var    rsp = JSON.parse(rsp);
                    }else{
                        var	rsp= rsp;
                    }
                    $("#hints").html('<p>订单属性修改成功！</p>');
                  	showMsg('hint');
                    getdetail();
                },
                error: function(msp){
                    if(typeof msp === 'string'){
                        var msp = JSON.parse(msp);
                    }else{
                        var	msp= msp;
                    }
                    if(msp.sub_code=='subuser.has-no-permission'){
                    	$("#hints").html('<p>该子帐号无此操作权限，请通过主帐号设置开通相应权限！</p>');
                      	showMsg('hint'); 
                    }else{
                        if(msp.sub_msg){
                        	$("#hints").html('<p>'+msp.sub_msg+'</p>');
                          	showMsg('hint');
                        }else{
                        	geterrorinfo('taobao.trade.ordersku.update',msp);
                        }
                    }
                }
            });
        }
    }
        function changetosp(num_id){
            QN.plugin.invoke({
                "cmd": "itemDetail",
                "param": {
                    iid:num_id
                },
                "category": "shangpinguanli"
            });
        }
        var rsult={};
       

    /******************************字符串清楚特殊字符*************************************/
    function clearBr(key)
    {
        key = key.replace(/<\/?.+?>/g,"");
        key = key.replace(/[\r\n]/g, "");
        key=key.replace(/(^\s*)|(\s*$)/g,""); /*消除首尾空格*/
        return key;
    }       
    </script>
    <!-- 我的发货地址。 -->
    <script id="selectaddr_template" type="text/x-handlebars-template">
		<option value="{{contact_id}}" {{#if get_def}}selected{{/if}}>{{province}},{{city}},{{country}},{{addr}},{{zip_code}},{{contact_name}},{{phone}},{{mobile_phone}}</option>
	</script>	
	<!-- 我的退货货地址。 -->
	<script id="selectbackaddr_template" type="text/x-handlebars-template">
		<option value="{{contact_id}}" {{#if cancel_def}}selected{{/if}}>{{province}},{{city}},{{country}},{{addr}},{{zip_code}},{{contact_name}},{{phone}},{{mobile_phone}}</option>
</script>	
    <script id="skudata_template" type="text/x-handlebars-template">
        <table class="sui-table table-bordered" >
            <tr><td>
                <div class="span2" style="text-align:center;"><a href="javascript:void(0);" onclick="changetosp('{{num_iid}}')"><img alt="商品图片" src="{{pic_path}}_80x80.jpg" width="60" align="middle" /></a>
                </div>
                <div class="span10"><p style="font-size:14px; margin:0;padding:0;"><a href="javascript:void(0);" onclick="changetosp('{{num_iid}}')">{{title}}</a></p>

                    <p style="margin:0;padding:0;color:gray;" >{{properties}}&nbsp;&nbsp;<b>{{price}} x{{num}}</b>
                     </p>
                </div>
                </td>
            </tr>
            <tr><td>
                <div class="span2" style="text-align:center;"> </div>
                <div class="span10">
                    <b>请选择新的属性：</b><br/>
                    <select id="selectsku"  onchange="radclick();">
                        {{#each skus}}
                      <!--  <label class="" style="display: inline;">
                            <input  name="radiosku" onclick="radclick();" value="{{properties}},{{price}},{{quantity}}" type="radio">
                            {{properties_name}}
                        </label>&nbsp;-->
                        <option value="{{properties}},{{price}},{{quantity}}" {{isprosku}}>{{properties_name}}</option>
                    {{/each}}
                    </select>
                    <p><b>价格：</b><span id="skuprice">0.00</span></p>
                    <p><b>库存：</b><span id="skunum">0</span></p>

                </div>
                </td>
            </tr>
        </table>
    </script>

    <script id="tdtid_template" type="text/x-handlebars-template">
        <p>订单编号：{{tid}}</p>
        <p>支付宝交易号：{{alipay_no}}</p>
        <p>成交时间：{{created}}</p>
        {{#if pay_time}}
        <p>付款时间：{{pay_time}}</p>
        {{/if}}
        {{#if end_time}}
        <p>确认时间：{{end_time}}</p>
        {{/if}}
    </script>
    <script id="closelist_template" type="text/x-handlebars-template"> 
        {{#each tditems}}
{{#if iscdclose}}
        <tr>
            <td width="5%"><input type="checkbox" name="closecheckcheckbox" checked=true value="{{oid}}" /></td>
            <td width="20%"><img alt="商品图片" src="{{pic_path}}_80x80.jpg" width="60" align="middle" /></td>
            <td class="80%"><h3 style="font-size:12px; margin:0; padding:0; line-height:14px;">{{title}}</h3>
                <p style="margin:0; padding:0;">{{price}} x{{num}}</p>
                <p style="margin:0; padding:0;">{{sku_properties_name}}</p>
                {{#if outer_sku_id}}
                <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_sku_id}}</p>
                {{else}}
                <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_iid}}</p>
                {{/if}}
            </td>
        </tr>
{{/if}}
        {{/each}}
    </script>
    <script id="tditem_template" type="text/x-handlebars-template">
        <thead>
        <tr>
            <th width="62%" colspan="2">宝贝</th>
            <th width="16%">状态</th>
            <th width="23%">优惠</th>
        </tr>
        </thead>
        {{#each tditems}}
        <tr>
            <td width="15%" style="text-align:center;"><a href="javascript:void(0);" onclick="changetosp('{{num_iid}}')">
					{{#if pic_path}}
						<img alt="商品图片" src="{{pic_path}}_80x80.jpg" width="60" align="middle" /></a>
					{{else}}
						<img alt="商品图片" src="http://cdn.zzgdapp.com/trade/web/images/imgnull.gif" width="60" align="middle" /></a>
						{{/if}}
            </td>
            <td><p style="font-size:14px; margin:0;padding:0;"><a href="javascript:void(0);" onclick="changetosp('{{num_iid}}')">{{title}}</a></p>
                <p style="margin:3px 0 0 0;padding:0;"><b>{{price}} x{{num}}</b></p>
                {{#if sku_properties_name}}
                <p style="margin:0;padding:0;color:gray;" >{{sku_properties_name}}
                    &nbsp;&nbsp; <a href="javascript:void(0);" onclick="editsku('{{oid}}','{{num_iid}}','{{pic_path}}','{{title}}','{{price}}','{{num}}','{{sku_properties_name}}');">{{editpro  status}}</a>
                </p>
                {{/if}}
				{{#if outer_sku_id}}
				<p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_sku_id}}</p>
				{{else}}
                <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_iid}}</p>
				{{/if}}
				</td>
            <td><p style="margin:0;padding:0;color:red;" >{{refundName refund_status status}}</p>
            {{#if rurl}}
              <br/> <a href="{{rurl}}" class="sui-btn but-small btn-primary">退款信息</a>
             {{/if}}
            </td>
            <td><p>卖家优惠：{{getFee adjust_fee}}</p>
				<p>{{oidsptil}}</p>
				<p>信用卡支付：<font color="red">{{iscardmoney}}</font></p>
			</td>
        </tr>
            {{/each}}		
    </script>
	
	<script id="jifeninfo_template" type="text/x-handlebars-template">
		<table>
		<tr>
			<td width="25%">运费险：<font color="red">{{yunfeixian}}</font></td>
			<td width="25%">交易佣金：<font color="red">{{jiaoyimoney}}</font></td>
			<td width="25%">买家使用积分：<font color="red">{{buerjifen}}</font></td>
			<td width="25%"> 发票抬头：<font color="red">{{receipthead}}</font></td>		
		</tr>
		<tr></tr><!--中间需要空格-->
		<tr>
			<td width="25%">货到付款费用：<font color="red">{{huodaomoney}}</font></td>
			<td width="25%">实际使用积分：<font color="red">{{shijishiyongjifen}}</font></td>
			<td width="30%">买家获得积分：<font color="red">{{buyerGetjifen}}</font></td>			
		</tr>
	</table>
    </script>

     <script id="tdwuliu_template" type="text/x-handlebars-template">
        <h5 >收货和物流信息&nbsp;&nbsp;
            {{#if wlflase}}
            <button class="sui-btn btn-primary"  onclick="sendwuliuw('{{buyer_nick}}','{{company_name}},{{out_sid}}');" >发送物流信息到旺旺</button>
            {{/if}}
        </h5>
        <p><span title="请使用Ctrl+C复制，Ctrl+V粘帖。">收货地址：    {{receiver_name}} ，{{receiver_mobile}} ，{{receiver_phone}} ， {{receiver_state}} {{receiver_city}} {{receiver_district}} {{receiver_address}} ，{{receiver_zip}}</span>
            {{#if wleditt}}
            <button class="sui-btn btn-primary" onclick="butrefresh()" data-toggle="modal">修改地址</button>
            {{/if}}
        </p>
        <p>运送方式：  {{shipping_type}}</p>
        <p>物流公司名称：  {{company_name}}
			{{#if isresend}}
          <!--  <button class="sui-btn btn-primary" onclick="wangwangPC('{{buyer_nick}}'" >发送物流公司和单号
                </button>-->
            <button class="sui-btn btn-primary" onclick="toresend('{{company_name}}');" id="resend">发货修改
            </button>
            {{/if}}</p>
{{#if out_sid}}
       		 <p>运单号：    {{out_sid}}
{{/if}}
            {{#if wlflase}}
            <!--<button class="sui-btn btn-primary" onclick="showwltab();" id="wlbut">点击查看物流信息
            </button>-->
            {{/if}}
        </p>
    </script>

    <script id="tdwldatas_template" type="text/x-handlebars-template">
        <h5 >物流动态</h5>
		{{#if wuliuinfo}}
				<p class="dintro">{{wuliuinfo}}</p>
			{{/if}}
		{{#each tracelists}}
        <p class="dintro">{{status_time}} {{status_desc}}</p>
		{{/each}}
    </script>

    <script id="pingjiadata_template" type="text/x-handlebars-template">
        {{#each tditems}}
        <table class="sui-table table-bordered" >
            <tr>
                <td width="20%"><img alt="商品图片" src="{{pic_path}}_80x80.jpg" width="60" align="middle" /></td>
                <td width="80%"><h3 style="font-size:12px; margin:0; padding:0; line-height:14px;">{{title}}</h3>
                    <p style="margin:0; padding:0;">{{price}} x{{num}}</p>
                    <p style="margin:0; padding:0;">{{sku_properties_name}}</p>
                    {{#if outer_sku_id}}
                    <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_sku_id}}</p>
                    {{else}}
                    <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_iid}}</p>
                    {{/if}}
                </td>
            </tr>
        </table>
        <input style="margin-left: 20px"  type="radio"    name="rate{{oid}}" value="good"  checked/><span   class="lbl"><img src="http://cdn.zzgdapp.com/trade/web/images/good.png" width="12" alt="好评"></span>
        <input  style="margin-left: 20px" type="radio"    name="rate{{oid}}" value="neutral"  /><span   class="lbl"><img src="http://cdn.zzgdapp.com/trade/web/images/neutral.png" width="12" alt="中平"></span>
        <input style="margin-left: 20px"  type="radio"    name="rate{{oid}}" value="bad"  /><span   class="lbl"><img src="http://cdn.zzgdapp.com/trade/web/images/bad.png" width="12" alt="差评"></span>
        <span>&nbsp;&nbsp;&nbsp;&nbsp;选择评语:&nbsp;&nbsp;</span>
        <select onchange="Pconchoice('{{oid}}')" style="width: 260px;" class="conpj" id ="conpj{{oid}}">
        </select>
        <textarea class="span12" id="trate{{oid}}" placeholder="" style="margin-top: 5px;width:400px" name="initpcon"></textarea>
        {{/each}}
    </script>

    <script id="sendlist_template" type="text/x-handlebars-template">
        {{#each tditems}}
{{#if iscdsend}}
        <tr>
            <td width="5%"><input type="checkbox" name="batchcheckbox" checked=true value="{{oid}}"/></td>
            <td width="15%"><img alt="商品图片" src="{{pic_path}}_80x80.jpg" width="60" align="middle" /></td>
            <td width="80%"><h3 style="font-size:12px; margin:0; padding:0; line-height:14px;">{{title}}</h3>
                <p style="margin:0; padding:0;">{{price}} x{{num}}</p>
                <p style="margin:0; padding:0;">{{sku_properties_name}}</p>
                {{#if outer_sku_id}}
                <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_sku_id}}</p>
                {{else}}
                <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_iid}}</p>
                {{/if}}
            </td>
        </tr>
{{/if}}
        {{/each}}
        <tr>
            <td colspan="3"><p class="font_wsl" style="margin:0; padding:0; line-height:1.2em">收货地址：<a onclick="wangwang('{{buyer_nick}}');"  href="javascript:void(0);"><img border="0" src="http://amos.alicdn.com/realonline.aw?v=2&uid={{buyer_nick}}&site=cntaobao&s=2&charset=utf-8"/>{{buyer_nick}}</a>&nbsp;,{{receiver_name}} ，{{receiver_phone}} ，{{receiver_mobile}} ， {{receiver_state}} {{receiver_city}} {{receiver_district}} {{receiver_address}} ，{{receiver_zip}}</p></td>
        </tr>
        {{#if sendsmessage}}
        <tr>
            <td colspan="3">
                <p ><b>卖家备注：</b>{{sendsmessage}}</p>
                {{#if sendbmessage}}
                <p ><b>买家留言：</b>{{sendbmessage}}</p>
                {{/if}}
            </td>
        </tr>
        {{else}}
        {{#if sendbmessage}}
        <tr>
            <td colspan="3">
                <p ><b>买家留言：</b>{{sendbmessage}}</p>
            </td>
        </tr>
        {{/if}}
        {{/if}}
    </script>
<script id="ontrade_template" type="text/x-handlebars-template"> 
<option value="{{code}}" {{s}}>{{name}}</option>
</script>
    <script id="pricebd_template" type="text/x-handlebars-template">


        <p style="margin:0; padding:0;">订单原价（不含运费）：{{total_fee}}元</p>
        <div class="sui-row-fluid">
            <div class="span2">邮费（元）:</div>
            <div class="span10">
                <div class="input-append">
                    <input type="text" id="postval" value="{{post_fee}}"  onchange="changepost();"  /><button class="sui-btn btn-warning" type="button" onclick="twopostfree();">免运费</button>
                </div>
            </div>
        </div>
        <p style="color:#999; margin:0; padding:0;">收货地址： {{receiver_name}} ，{{receiver_phone}} ，{{receiver_mobile}} ， {{receiver_state}} {{receiver_city}} {{receiver_district}} {{receiver_address}} ，{{receiver_zip}}</p>
        <table class="sui-table table-striped table-bordered table-hover" style="margin-top:10px;">
            <thead >
            <tr>
                <th width="50%">宝贝</th>
                <th width="20%">单价（元）*数量</th>
                <th width="30%">涨价或折扣</th>
            </tr>
            </thead>
            {{#each tditems}}
            <tr>

                <td>{{title}}
                    <p style="margin:0; padding:0; color:#999;">{{sku_properties_name}}</p>
                    {{#if outer_sku_id}}
                    <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_sku_id}}</p>
                    {{else}}
                    <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_iid}}</p>
                    {{/if}}
                </td>
                <td style="text-align:center;">{{price}}* {{num}}
                    <p style="margin:0; padding:0;">= <span style="font-size:14px; font-weight:800; color:#ff0000;">{{itemtotal}}</span></p></td>
                <td>
                    <input  type="text" id="rebate-{{oid}}" size="4"  onchange="changezhe('{{oid}}','{{price}}','{{num}}',{{zhe_fee}});" value="{{zhe}}" style="width:40px;"/>折=<input  type="text" name="slider-{{oid}}" id="slider-{{oid}}"  size="5" value="{{zhe_fee}}"  onchange="changezhefee('{{oid}}',{{zhe_fee}});" style="width:40px;"/>
                </td>
            </tr>
            {{/each}}
        </table>
        <p style="margin:0; padding:0;" id="maijiashifu">{{maijiashifu}}</p>
        <div class="alert" style="text-align:left;">				
            <p style="margin:0; padding:0;">买家实付 =原价 + 运费 + 涨价或折扣 + 店铺优惠</p>
            <p style="margin:0; padding:0;">邮费为0时货到付款服务费将由卖家承担。</p></div>

    </script>
    <script id="codsendlist_template" type="text/x-handlebars-template">
        {{#each tditems}}
        {{#if iscdsend}}
        <tr>
            <td width="20%"><img alt="商品图片" src="{{pic_path}}_80x80.jpg" width="60" align="middle" /></td>
            <td class="80%"><h3 style="font-size:12px; margin:0; padding:0; line-height:14px;">{{title}}</h3>
                <p style="margin:0; padding:0;">{{price}} x{{num}}</p>
                <p style="margin:0; padding:0;">{{sku_properties_name}}</p>
                {{#if outer_sku_id}}
                <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_sku_id}}</p>
                {{else}}
                <p style="margin:0;padding:0;color:gray;" >商家编码:{{outer_iid}}</p>
                {{/if}}
            </td>
        </tr>
        {{/if}}
        {{/each}}
        <tr>
            <td colspan="3"><p class="font_wsl" style="margin:0; padding:0; line-height:1.2em">收货地址：<a onclick="wangwang('{{buyer_nick}}');"  href="javascript:void(0);"><img border="0" src="http://amos.alicdn.com/realonline.aw?v=2&uid={{buyer_nick}}&site=cntaobao&s=2&charset=utf-8"/>{{buyer_nick}}</a>&nbsp;,{{receiver_name}} ，{{receiver_phone}} ，{{receiver_mobile}} ， {{receiver_state}} {{receiver_city}} {{receiver_district}} {{receiver_address}} ，{{receiver_zip}}</p></td>
        </tr>
        <!-- <tr>
             <td colspan="3"><p ><b>卖家备注：</b>{{sendsmessage}}</p><p ><b>买家留言：</b>{{sendbmessage}}</p></td>
         </tr>-->
        {{#if sendsmessage}}
        <tr>
            <td colspan="3">
                <p ><b>卖家备注：</b>{{sendsmessage}}</p>
                {{#if sendbmessage}}
                <p ><b>买家留言：</b>{{sendbmessage}}</p>
                {{/if}}
            </td>
        </tr>
        {{else}}
        {{#if sendbmessage}}
        <tr>
            <td colspan="3">
                <p ><b>买家留言：</b>{{sendbmessage}}</p>
            </td>
        </tr>
        {{/if}}
        {{/if}}
    </script>
<?php require_once ('app/views/public/footer.php');?>
</body>
</html>
